import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "agentes-ia-bloqueados-sites-comercio",
  title: "Agentes de IA para compras enfrentam bloqueio de Amazon, Delta e eBay",
  summary: "Levantamento mostra Amazon, Walmart, Delta, United, Yelp, eBay, Zillow e outros bloqueando agentes como Muse, Dots e Instinct, sem padrão claro sobre quando a barreira é intencional.",
  author: "Bruno Danello",
  sourceName: "TechCrunch",
  sourceUrl: "https://techcrunch.com/2026/10/06/the-next-hurdle-for-ai-agents-getting-websites-to-let-them-in/",
  date: "2026-10-06",
  publishedAt: "2026-10-06T18:45:00-03:00",
  imageQuery: "person shopping online laptop checkout",
  topic: "negocios",
  content: `
    <p>Agentes pessoais de inteligência artificial que prometem comprar produtos, reservar voos e fazer agendamentos em nome do usuário, como o Muse da Meta, o Dots da OpenAI e o Instinct, vêm enfrentando uma barreira recorrente: sites inteiros que bloqueiam o acesso desses agentes antes mesmo de a tarefa ser concluída. Segundo reportagem do <a href="https://techcrunch.com/2026/10/06/the-next-hurdle-for-ai-agents-getting-websites-to-let-them-in/" target="_blank" rel="noopener noreferrer nofollow">TechCrunch</a>, publicada nesta terça-feira (6), usuários relataram bloqueios em Amazon, Walmart, Delta, United, Yelp, eBay, Zillow, Pizza Hut, Adidas e até no próprio Google, com motivos que variam de decisão comercial deliberada a efeito colateral não intencional de sistemas de proteção contra bots.</p>
    <p>O caso mais extremo documentado pela reportagem é o do eBay, que chegou a suspender contas de usuários identificados como usando IA agêntica para navegar e comprar no site, tratando o comportamento automatizado como risco de fraude mesmo quando o dono da conta estava de fato por trás da compra. Já o Google bloqueou o Instinct justamente no momento em que o agente tentava ajudar o usuário a limpar a caixa de entrada do Gmail, uma tarefa doméstica, não comercial, o que sugere que parte dos bloqueios acontece sem distinção clara entre uso legítimo e abuso.</p>

    <h2>Entre decisão de negócio e efeito colateral de segurança</h2>
    <p>A reportagem aponta que parte dos bloqueios vem de serviços de proteção contra bots, como o da Cloudflare, que ajustou em 15 de setembro os padrões de defesa contra rastreadores automatizados, afetando também o tráfego legítimo de agentes de IA que tentam agir em nome de uma pessoa real. Esse tipo de barreira técnica não distingue facilmente entre um bot malicioso tentando raspar dados em massa e um agente pessoal fazendo uma única compra autorizada pelo próprio usuário, o que já havia motivado o <a href="/noticias/amazon-bloqueia-agente-ia-muse-meta-compras">bloqueio específico do Muse na Amazon em setembro</a>, quando a varejista alegou que o agente da Meta nunca pediu autorização e nem se identificava corretamente ao navegar pelo site.</p>
    <p>Já outros bloqueios parecem ser decisão comercial deliberada: a executiva da Delta Heena Chavda declarou à reportagem que a companhia aérea está "continuando a avaliar como novas tecnologias, incluindo agentes de IA externos, poderiam melhorar o engajamento com o cliente", frase que soa mais a uma posição de espera cautelosa do que a uma rejeição categórica. A tensão de fundo é clara: sites de comércio têm interesse em manter o controle sobre a experiência de compra, inclusive sobre qual produto é exibido primeiro ou qual promoção aparece na tela, algo que um agente de IA que navega direto ao ponto pode simplesmente ignorar.</p>

    <h2>Por que isso importa para quem já usa ou pensa em usar agentes de IA no Brasil</h2>
    <p>Para quem no Brasil já testa agentes de compras como forma de economizar tempo, como descrito no guia do Portal da AI sobre <a href="/artigos/agentes-de-ia-comprando-por-voce-comercio">agentes de IA comprando por você no comércio</a>, a notícia é um alerta prático: a tecnologia promete autonomia, mas a infraestrutura dos próprios sites de varejo e serviço ainda não está pronta para recebê-la de forma consistente, e um bloqueio pode acontecer sem aviso claro sobre o motivo. Isso é especialmente relevante para quem pretende empreender construindo ou revendendo esse tipo de automação, tema explorado no texto sobre <a href="/artigos/como-ganhar-dinheiro-criando-e-vendendo-agentes-de-ia-personalizados">como ganhar dinheiro criando e vendendo agentes de IA personalizados</a>: um agente que funciona hoje num site pode parar de funcionar da noite para o dia, sem qualquer mudança no código do próprio agente.</p>
    <p>Para pequenos negócios que avaliam abrir as portas para esse tipo de tráfego automatizado, a tensão também aparece do outro lado: aceitar agentes de IA como clientes pode significar mais vendas, mas também abre uma porta nova para fraude e abuso, risco que incentivos como o <a href="/noticias/cloudflare-monetization-gateway-pagamento-agentes-ia">Monetization Gateway da Cloudflare</a> tentam resolver cobrando explicitamente pelo acesso de agentes, em vez de simplesmente bloquear ou liberar tudo sem controle algum.</p>

    <h2>Parceiros de atendimento tentam criar um padrão comum</h2>
    <p>A reportagem cita empresas de atendimento ao cliente como Sierra, Genesys, Rocket, NiCE e Decagon trabalhando em conjunto no desenvolvimento de um padrão aberto para identificar e autenticar agentes de IA perante sites de terceiros, de forma parecida com o que já existe hoje para identificar navegadores e aplicativos legítimos. A ideia é permitir que um site saiba, de forma verificável, que aquele tráfego automatizado representa de fato um cliente real que autorizou a ação, sem depender de cada empresa criar sua própria solução isolada.</p>
    <p>Enquanto esse padrão não existe de forma amplamente adotada, a recomendação prática para quem usa agentes de compra é simples: verificar sempre, manualmente, se a compra ou reserva foi realmente concluída, já que um bloqueio silencioso pode deixar a tarefa pela metade sem gerar qualquer erro visível para quem delegou a ação ao agente. A própria Meta reconheceu o problema em comunicado citado pela reportagem, afirmando que "recusar um agente pessoal significa recusar o cliente que está por trás dele", numa tentativa de pressionar sites parceiros a tratarem esse tráfego com as mesmas regras aplicadas a um cliente humano comum.</p>

    <h2>Um problema parecido com o que a web já viveu com os primeiros robôs de busca</h2>
    <p>A disputa atual entre sites de comércio e agentes de IA lembra, em menor escala, o período em que mecanismos de busca como o Google passaram a indexar páginas automaticamente no fim dos anos 1990: no início, muitos sites bloqueavam qualquer tráfego automatizado por padrão, até que protocolos como o <em>robots.txt</em> e acordos comerciais específicos criaram um equilíbrio entre deixar o rastreador entrar (o que trazia tráfego de busca) e proteger o site de abuso. Com agentes de compra, a equação é mais delicada porque o agente não só lê a página, ele age sobre ela, finalizando compras e preenchendo dados de pagamento, o que eleva o risco percebido por quem opera o site de destino.</p>
    <p>Enquanto não existe um equivalente ao robots.txt para agentes transacionais, cada site decide sozinho onde traçar a linha, e o resultado é a colcha de retalhos que a reportagem documenta: Amazon e eBay com postura mais restritiva, Delta em modo de observação, e outras empresas como Walmart que, segundo o levantamento, chegaram a reconsiderar o bloqueio inicial depois de pressão pública. Essa inconsistência entre concorrentes do mesmo setor dificulta ainda mais a vida de quem desenvolve um agente de compras pensando em cobrir várias lojas ao mesmo tempo, já que o comportamento esperado em um site pode ser completamente diferente do site seguinte.</p>

    <h2>O que isso diz sobre a maturidade real dos agentes de IA hoje</h2>
    <p>Fora o atrito técnico e comercial, o episódio também serve como um lembrete de que a promessa de "IA que faz tudo por você" ainda depende de uma camada inteira de infraestrutura que não foi desenhada pensando em agentes autônomos como usuários finais. Páginas de checkout, sistemas de autenticação de dois fatores e verificações de CAPTCHA foram construídos para distinguir humano de robô justamente para impedir esse tipo de automação, o que cria uma barreira estrutural difícil de contornar sem cooperação explícita do lado do site. Enquanto esse atrito não for resolvido de forma ampla, agentes como Muse, Dots e Instinct continuarão funcionando de forma inconsistente, bem em um site e mal no seguinte, o que limita o quanto esse tipo de produto pode realmente substituir a navegação manual no curto prazo.</p>
  `,
};
