import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "aws-amazon-fim-nda-data-centers-bilhao-comunidades",
  title: "AWS acaba com NDAs em data centers e promete US$ 1 bi a comunidades",
  summary:
    "Matt Garman, CEO da AWS, anuncia fim de acordos de confidencialidade com governos e programa de US$ 1 bilhão após mais de 100 moratórias locais contra data centers de IA.",
  author: "Bruno Danello",
  sourceName: "Amazon (About Amazon)",
  sourceUrl:
    "https://www.aboutamazon.com/news/company-news/amazon-data-centers-built-together",
  date: "2026-10-02",
  content: `
    <p>Matt Garman, CEO da Amazon Web Services (AWS), anunciou em 2 de outubro que a empresa deixará de usar acordos de confidencialidade, os chamados NDAs, em negociações com órgãos governamentais sobre novos projetos de data centers. Segundo o <a href="https://www.aboutamazon.com/news/company-news/amazon-data-centers-built-together" target="_blank" rel="noopener noreferrer nofollow">anúncio publicado no site oficial da Amazon</a>, a mudança busca responder a uma onda crescente de reclamações sobre falta de transparência que já levou mais de 100 municípios e estados americanos a considerar moratórias contra a instalação desses centros de dados voltados a inteligência artificial.</p>
    <p>Além do fim dos NDAs, Garman anunciou um programa batizado de "Built Together", com investimento superior a US$ 1 bilhão ao longo dos próximos cinco anos em comunidades que hospedam data centers da AWS. A empresa também se comprometeu a divulgar anualmente, de forma pública, dados sobre consumo e eficiência de energia, consumo e eficiência de água, e o percentual de energia livre de carbono usado em cada instalação, métricas que antes costumavam ficar protegidas justamente pelos acordos de confidencialidade que a empresa agora promete abandonar.</p>

    <h2>Por que as moratórias contra data centers se multiplicaram</h2>
    <p>O anúncio da AWS chega poucas semanas depois de o prefeito de South Bend, no estado americano de Indiana, assinar ordens executivas proibindo funcionários da cidade de firmar NDAs com empresas de data center, depois que o diretor de obras públicas da cidade admitiu ter assinado um desses acordos com a própria AWS em 2023. O caso se tornou símbolo de uma tensão que vinha crescendo havia meses: comunidades reclamam que não conseguem avaliar o real impacto desses projetos gigantes em consumo de energia e água, nem negociar contrapartidas justas, porque os termos das negociações ficam protegidos por confidencialidade contratual.</p>
    <p>Essa pressão local se soma a um movimento mais amplo de resistência a data centers de IA nos Estados Unidos, que já levou estados como a Califórnia a aprovar legislação específica sobre o tema, caso do <a href="/noticias/newsom-decreto-ia-super-intelligencia-california">decreto do governador Gavin Newsom</a> que endureceu regras para empresas de inteligência artificial no estado. O ritmo de construção desses data centers tem sido puxado por investimentos bilionários de empresas como a própria Amazon, que fechou recentemente um <a href="/noticias/amazon-8-bilhoes-chips-nvidia-leaseback">acordo de leaseback de US$ 8 bilhões em chips da Nvidia</a> para expandir sua capacidade de computação, e pela Anthropic, que recebeu um <a href="/noticias/broadcom-emprestimo-42-bilhoes-anthropic-chips-tpu">empréstimo de US$ 42 bilhões da Broadcom</a> destinado a chips e infraestrutura de data center. Esse volume de investimento, concentrado em poucos anos, é justamente o que tem sobrecarregado a infraestrutura elétrica e hídrica de cidades menores nos Estados Unidos, alimentando a reação política que a AWS agora tenta conter.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem usa ferramentas de IA no trabalho ou acompanha o setor como empreendedor no Brasil, essa mudança de postura da AWS é um sinal de que o custo político de expandir infraestrutura de inteligência artificial está subindo, mesmo nos Estados Unidos, onde esses projetos cresceram sem muito entrave nos últimos anos. Isso importa porque boa parte da capacidade de computação que sustenta modelos como o Gemini, o GPT ou o Claude, usados diariamente por profissionais e negócios brasileiros, depende diretamente desses data centers físicos: quanto mais lenta ou cara fica a expansão dessa infraestrutura nos Estados Unidos, maior a pressão para que o custo de rodar modelos de IA em escala também suba, o que pode se refletir em preços de API e assinaturas no Brasil.</p>
    <p>Também vale observar o padrão que a AWS está tentando estabelecer: transparência pública sobre consumo de energia e água como resposta a pressão da comunidade, em vez de simplesmente negociar caso a caso com cada prefeitura. Esse tipo de compromisso tende a se tornar referência para outras gigantes de nuvem e IA que competem pelos mesmos terrenos e pela mesma energia elétrica, incluindo Microsoft, Google e Meta, todas em plena corrida por capacidade computacional para treinar e rodar modelos cada vez maiores. Empresas brasileiras que dependem de provedores de nuvem americanos para hospedar aplicações de IA devem acompanhar se esse movimento de maior transparência se espalha, já que isso pode afetar prazos de expansão de data centers planejados para atender clientes da América Latina.</p>

    <h2>O que observar nos próximos meses</h2>
    <p>Vale acompanhar se outras empresas de nuvem seguem o mesmo caminho da AWS, abandonando NDAs e publicando métricas de consumo de energia e água em seus próprios projetos de data center, ou se o movimento fica isolado como resposta pontual da Amazon à repercussão negativa em cidades como South Bend. Também é importante observar se as mais de 100 moratórias municipais e estaduais mencionadas no anúncio avançam mesmo depois da mudança de postura da AWS, ou se o compromisso de transparência é suficiente para esfriar a resistência política local nos Estados Unidos.</p>
    <p>No Brasil, onde grandes empresas de tecnologia também vêm anunciando planos de expansão de data centers e infraestrutura de IA, o episódio da AWS pode servir de referência para como prefeituras e governos estaduais brasileiros devem negociar esses projetos no futuro, com mais atenção a cláusulas de confidencialidade e a compromissos públicos de transparência ambiental. Isso se conecta diretamente ao debate sobre <a href="/artigos/lei-de-ia-no-brasil-o-que-muda-para-quem-usa">o que muda com a regulação de IA no Brasil</a>, já que a infraestrutura física que sustenta a inteligência artificial tende a se tornar, cada vez mais, parte central dessas discussões regulatórias, ao lado de temas mais tradicionais como direitos autorais, transparência algorítmica e proteção de dados pessoais.</p>

    <div class="callout-box"><span class="callout-label">Para lembrar</span>Matt Garman, CEO da AWS, anunciou em 2 de outubro de 2026 o fim do uso de acordos de confidencialidade (NDAs) em negociações com governos sobre data centers, além de um programa de US$ 1 bilhão em cinco anos para comunidades que hospedam essas instalações. A empresa também vai publicar anualmente dados de consumo de energia, água e percentual de energia livre de carbono, em resposta a mais de 100 moratórias locais consideradas nos Estados Unidos contra a expansão de data centers de IA.</div>
  `,
};
