import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "california-newsom-leis-ia-trabalhadores",
  title: "Califórnia proíbe demissão só por IA e exige aviso em layoff automatizado",
  summary:
    "Newsom sancionou leis que travam IA em despedimentos, biometria emocional e cobram aviso quando um sistema causa demissão em massa.",
  author: "Bruno Danello",
  sourceName: "Associated Press",
  sourceUrl: "https://www.click2houston.com/news/politics/2026/09/30/california-gov-gavin-newsom-signs-laws-to-protect-workers-from-ai-risks/",
  date: "2026-09-30",
  content: `
    <p>O governador da Califórnia, Gavin Newsom, sancionou nesta terça-feira (30) um pacote de leis voltado a limitar o uso de inteligência artificial em decisões sobre o emprego de trabalhadores no estado. Segundo reportagem da <a href="https://www.click2houston.com/news/politics/2026/09/30/california-gov-gavin-newsom-signs-laws-to-protect-workers-from-ai-risks/" target="_blank" rel="noopener noreferrer nofollow">Associated Press</a>, as novas regras proíbem empresas de usar IA para prever o "estado emocional" de um funcionário a partir de dados biométricos, impedem que uma demissão seja decidida só por um sistema automatizado, sem revisão humana, e obrigam o empregador a avisar por escrito quando um corte de pessoal, uma demissão em massa ou uma relocação de equipe for causado por IA.</p>

    <p>As leis fazem parte de um movimento mais amplo da Califórnia, que já vinha regulando o uso de IA em áreas como saúde e educação e agora avança para o mercado de trabalho. Newsom também assinou, dias antes, uma lei que exige avaliação de risco de chatbots de IA voltados ao público, e editou uma ordem executiva determinando que agências estaduais ampliem o acompanhamento dos efeitos da automação sobre o emprego e adaptem programas de treinamento profissional. "A IA deveria expandir oportunidades, não vir à custa de trabalhadores e famílias", disse o governador em comunicado, acrescentando que "a Califórnia está colocando as pessoas no centro" enquanto a tecnologia reorganiza o ambiente de trabalho.</p>

    <h2>Por que a Califórnia virou o laboratório da regulação de IA nos EUA</h2>
    <p>A Califórnia concentra as sedes de boa parte dos grandes laboratórios de IA (OpenAI, Google, Meta, Nvidia e a própria Anthropic têm operação relevante no estado), o que faz de suas leis estaduais um termômetro de para onde a regulação pode caminhar no resto do país, já que não existe hoje uma lei federal específica sobre agentes de IA no emprego nos Estados Unidos. Isso coloca a Califórnia na linha de frente justamente no momento em que o governo Trump assinou, dias antes, um acordo voluntário na Casa Branca com grandes empresas de IA, que o <a href="/noticias/trump-ceos-ia-assinam-acordo-autorregulacao-casa-branca">Portal da AI já cobriu</a>, e que aposta em autorregulação da indústria em vez de lei federal. O contraste entre os dois caminhos (regulação estadual obrigatória de um lado, compromisso voluntário federal do outro) é parte do motivo pelo qual Newsom chegou a dizer que pode convocar uma sessão especial da assembleia estadual caso o governo federal continue sem avançar em uma política nacional.</p>
    <p>O momento também não é aleatório. Um relatório recente da McKinsey, que o <a href="/noticias/mckinsey-11-milhoes-trabalhadores-ia-2035">Portal da AI detalhou em reportagem própria</a>, projeta que 11 milhões de trabalhadores nos Estados Unidos vão precisar trocar de função até 2035 por conta da automação com IA, e episódios de agentes autônomos "fora de controle", como os mais de 15 incidentes de segurança ligados à OpenAI que também já noticiamos, alimentam a desconfiança de sindicatos e legisladores sobre dar autonomia demais a sistemas automatizados dentro de decisões que afetam diretamente a vida de uma pessoa, como manter ou perder o emprego.</p>

    <h2>Por que isso importa para você</h2>
    <p>Mesmo quem trabalha ou contrata no Brasil sente o efeito dessas leis indiretamente, porque grande parte das ferramentas de IA usadas aqui (de sistemas de recrutamento automatizado a plataformas de gestão de equipe) é desenvolvida por empresas sediadas justamente na Califórnia, e tendem a ajustar o produto globalmente quando uma lei forte muda regras em casa, em vez de manter versões separadas por país. Se você usa IA para triagem de currículos, avaliação de desempenho ou qualquer etapa que possa levar a uma demissão, vale revisar hoje se existe revisão humana real no processo, e não apenas um carimbo formal em cima de uma decisão que o algoritmo já tomou, porque esse tipo de prática é exatamente o alvo das novas leis californianas e tende a se tornar padrão esperado em qualquer empresa séria, mesmo fora dos Estados Unidos.</p>
    <p>Para quem é funcionário e lida com ferramentas de produtividade com IA no dia a dia, a notícia também é um bom gatilho para entender melhor como IA e automação devem (ou não deveriam) decidir sozinhas sobre carreira. Nosso guia sobre <a href="/artigos/empregos-que-a-ia-vai-transformar-como-se-preparar">empregos que a IA vai transformar e como se preparar</a> mostra funções mais expostas à automação, e o texto sobre <a href="/artigos/como-humanos-e-agentes-de-ia-vao-trabalhar-juntos-no-futuro">como humanos e agentes de IA vão trabalhar juntos no futuro</a> ajuda a entender onde a lógica de "revisão humana obrigatória", que agora é lei na Califórnia, já é praticada por empresas mais maduras no uso da tecnologia.</p>

    <h2>O que fazer se a automação já estiver mudando sua rotina de trabalho</h2>
    <p>Se você sente que a IA já está reduzindo demanda pela sua função específica, ou vê sinais de que uma reestruturação baseada em automação pode estar vindo, vale se antecipar em vez de esperar um comunicado oficial. Nosso guia de <a href="/artigos/como-se-recolocar-no-mercado-depois-de-ser-substituido-por-automacao">como se recolocar no mercado depois de ser substituído por automação</a> traz um passo a passo prático, e o texto sobre <a href="/artigos/como-migrar-de-carreira-para-area-de-ia">como migrar de carreira para a área de IA</a> mostra um caminho concreto para quem quer virar o jogo e passar a trabalhar com a tecnologia, em vez de competir contra ela.</p>
    <p>Do lado regulatório, vale acompanhar se outros estados americanos (e eventualmente outros países) replicam o modelo californiano de exigir aviso formal e revisão humana em decisões automatizadas de emprego, algo que já discutimos no contexto de um <a href="/noticias/warren-investiga-isencao-fiscal-ia-big-tech">escrutínio político maior sobre como as big techs de IA operam nos EUA</a>. No Brasil, a Lei Geral de Proteção de Dados (LGPD) já prevê o direito de revisão humana em decisões automatizadas que afetem significativamente uma pessoa, mas a fiscalização específica sobre demissões causadas por IA ainda é incipiente, o que torna o caso californiano uma referência prática de como esse tipo de regra pode (e provavelmente vai) ficar mais detalhada por aqui também.</p>
  `,
};
