import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "elevenlabs-dobra-avaliacao-22-bilhoes",
  title: "ElevenLabs dobra avaliação para US$ 22 bilhões em oito meses",
  summary:
    "Startup de vozes sintéticas faz segunda oferta de recompra de ações de funcionários e se torna uma das startups europeias mais valiosas do setor.",
  author: "Bruno Danello",
  sourceName: "TechCrunch",
  sourceUrl: "https://techcrunch.com/2026/09/30/ai-voice-startup-elevenlabs-doubles-valuation-to-22b/",
  date: "2026-09-30",
  content: `
    <p>A ElevenLabs, startup de Nova York e Londres conhecida por gerar vozes sintéticas realistas e clonagem de voz, anunciou nesta terça-feira que dobrou sua avaliação de mercado para US$ 22 bilhões, ante os US$ 11 bilhões de fevereiro deste ano. O salto veio por meio de uma oferta de recompra de ações de funcionários no valor de US$ 300 milhões, liderada pelas gestoras Wellington e T. Rowe Price, segundo apuração do <a href="https://techcrunch.com/2026/09/30/ai-voice-startup-elevenlabs-doubles-valuation-to-22b/" target="_blank" rel="noopener noreferrer nofollow">TechCrunch</a>.</p>

    <p>É a segunda vez que a empresa realiza esse tipo de operação, que permite a funcionários venderem parte das ações que já acumularam sem esperar por um IPO. A primeira aconteceu em setembro de 2025, quando a ElevenLabs foi avaliada em US$ 6,6 bilhões. Em um ano, portanto, a avaliação da companhia mais que triplicou, consolidando-a como uma das startups de IA mais valiosas da Europa.</p>

    <h2>Por que empresas de IA estão usando essa manobra financeira</h2>
    <p>Diferente de uma rodada de captação tradicional, em que a empresa recebe dinheiro novo em troca de ações, a oferta de recompra (tender offer, no termo em inglês) funciona como uma forma de dar liquidez a quem já trabalha na empresa, permitindo que esses funcionários vendam uma fatia das ações que receberam como parte da remuneração para investidores institucionais dispostos a pagar por elas. Segundo o TechCrunch, esse tipo de programa virou uma ferramenta comum de retenção entre startups de IA de alto crescimento, justamente para evitar que talentos valiosos deixem a empresa em busca de liquidez em concorrentes. Os investidores institucionais que entram nessas operações, como a Wellington e a T. Rowe Price neste caso, normalmente pretendem manter as ações até um eventual IPO da empresa.</p>
    <p>A ElevenLabs foi fundada em 2022 e rapidamente se tornou referência em geração de voz por IA, tanto para dublagem e narração quanto para agentes de atendimento por voz. A empresa já havia lançado em setembro o modelo <a href="/noticias/elevenlabs-lanca-v4-clonagem-voz-90-idiomas">Eleven v4, com clonagem de voz em mais de 90 idiomas</a>, e também fechou uma parceria de licenciamento de catálogo musical com a <a href="/noticias/universal-music-elevenlabs-plataforma-ia-musical-licenciada">Universal Music para uma plataforma de IA musical</a>, movimentos que ajudam a explicar o apetite de investidores pela empresa.</p>

    <h2>Um mercado de voz sintética cada vez mais disputado</h2>
    <p>A disparada na avaliação da ElevenLabs acontece num momento em que o mercado de voz gerada por IA está mais concorrido do que nunca. Grandes laboratórios como OpenAI, Google e Anthropic têm investido pesado em recursos de voz dentro de seus próprios produtos, e startups especializadas como a Tavus, que lançou recentemente o modelo de renderização humana em tempo real <a href="/noticias/tavus-lanca-phoenix-4-5-renderizacao-humana-tempo-real">Phoenix-4.5</a>, também disputam espaço nesse nicho. A aposta dos investidores é que, apesar da concorrência crescente, a demanda por voz sintética de qualidade profissional (para dublagem, audiolivros, atendimento automatizado e até trilhas narradas) ainda está longe de se esgotar, especialmente à medida que mais empresas adotam agentes de voz para interações com clientes.</p>
    <p>Vale notar que a avaliação da ElevenLabs em oito meses praticamente dobrou, um ritmo de crescimento que poucas empresas de qualquer setor conseguem sustentar, e que reflete uma característica comum entre as líderes de IA generativa em 2026: investidores institucionais estão dispostos a pagar múltiplos cada vez mais altos sobre receita atual, apostando que o mercado de voz e áudio sintético ainda está em estágio inicial de adoção corporativa. Esse tipo de aposta tem precedente recente em outras categorias de IA, como mostrou a disparada de avaliação da Snorkel AI, que triplicou seu valor de mercado para US$ 3,5 bilhões em meio à corrida por dados de treinamento de qualidade, outro sinal de que o apetite por infraestrutura de IA segue aquecido mesmo quando o produto final não chega diretamente ao consumidor comum.</p>

    <h3>Como funciona o modelo de negócio por trás da clonagem de voz</h3>
    <p>A ElevenLabs cobra por volume de caracteres convertidos em áudio, com planos que vão de uso gratuito limitado até contratos corporativos sob medida para empresas que precisam de milhares de horas de narração ou de agentes de atendimento por voz rodando em escala. É esse modelo recorrente, somado à licença de vozes para parceiros de mídia e estúdios, que sustenta parte do otimismo dos investidores: diferente de uma ferramenta usada uma vez e esquecida, voz sintética tende a virar parte permanente do fluxo de produção de quem a adota, seja uma produtora de conteúdo, uma emissora de rádio ou um call center.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você usa ferramentas de IA para criar conteúdo em áudio, seja <a href="/artigos/ia-para-audio-criar-podcasts-e-narracoes-profissionais">narrar podcasts, dublar vídeos ou montar audiolivros</a>, essa avaliação bilionária é um indicador de que o investimento em voz sintética de alta qualidade deve continuar acelerado nos próximos anos, o que tende a significar mais recursos, mais idiomas suportados e preços mais competitivos chegando ao mercado brasileiro. A ElevenLabs já é hoje uma das ferramentas mais usadas por criadores de conteúdo e pequenas produtoras no Brasil justamente pela qualidade da clonagem de voz em português, e esse aporte reforça a capacidade da empresa de continuar expandindo esse suporte.</p>
    <p>Há também um ponto de atenção para quem trabalha com marca pessoal ou reputação online: quanto mais barata e acessível fica a clonagem de voz de alta qualidade, maior o risco de uso indevido por golpistas, que já usam vozes sintéticas para fraudes envolvendo familiares e falsas urgências financeiras no Brasil. Vale a pena entender como identificar esse tipo de manipulação, um tema que nosso guia sobre <a href="/artigos/deepfakes-ia-identificar-conteudo-falso-proteger-reputacao">deepfakes e como identificar conteúdo falso</a> explica em detalhe, inclusive com dicas práticas para quem precisa proteger a própria voz e imagem.</p>
    <div class="callout-box">
      <span class="callout-label">Fique de olho</span>
      Antes de clonar sua própria voz ou a de um cliente para um projeto comercial, confirme sempre que há consentimento explícito e registrado, já que o uso indevido de voz sem autorização é um dos tipos de disputa que mais tem crescido entre criadores, artistas e gravadoras em 2026.
    </div>

    <h2>Por que isso importa para você</h2>
    <p>Se você usa ferramentas de IA para criar conteúdo em áudio, seja <a href="/artigos/ia-para-audio-criar-podcasts-e-narracoes-profissionais">narrar podcasts, dublar vídeos ou montar audiolivros</a>, essa avaliação bilionária é um indicador de que o investimento em voz sintética de alta qualidade deve continuar acelerado nos próximos anos, o que tende a significar mais recursos, mais idiomas suportados e preços mais competitivos chegando ao mercado brasileiro. A ElevenLabs já é hoje uma das ferramentas mais usadas por criadores de conteúdo e pequenas produtoras no Brasil justamente pela qualidade da clonagem de voz em português, e esse aporte reforça a capacidade da empresa de continuar expandindo esse suporte.</p>
    <p>Há também um ponto de atenção para quem trabalha com marca pessoal ou reputação online: quanto mais barata e acessível fica a clonagem de voz de alta qualidade, maior o risco de uso indevido por golpistas, que já usam vozes sintéticas para fraudes envolvendo familiares e falsas urgências financeiras no Brasil. Vale a pena entender como identificar esse tipo de manipulação, um tema que nosso guia sobre <a href="/artigos/deepfakes-ia-identificar-conteudo-falso-proteger-reputacao">deepfakes e como identificar conteúdo falso</a> explica em detalhe, inclusive com dicas práticas para quem precisa proteger a própria voz e imagem.</p>

    <h2>O que observar daqui para frente</h2>
    <p>Vale acompanhar se a ElevenLabs vai seguir o caminho de outras startups de IA de grande porte, como a Anthropic, que recentemente <a href="/noticias/anthropic-ipo-prospecto-vazado-2-trilhoes">revelou preparativos para abertura de capital</a>, rumo a um eventual IPO nos próximos anos, já que investidores institucionais costumam entrar nesse tipo de oferta de recompra justamente apostando nesse desfecho. Também é um bom momento para observar se concorrentes diretos no mercado de voz sintética, como a própria Tavus e grandes laboratórios de modelos de fronteira, vão anunciar rodadas ou avaliações comparáveis nos próximos meses, sinalizando se o apetite por IA de voz é uma tendência isolada da ElevenLabs ou um movimento mais amplo do setor.</p>
  `,
};
