import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "github-copilot-computer-use-desktop-preview",
  title: "GitHub Copilot ganha controle de apps do computador em pré-lançamento",
  summary:
    "Recurso de computer use deixa o Copilot clicar, digitar e navegar em qualquer programa de Windows ou Mac, mesmo sem API, e exige aprovação prévia do usuário para cada app.",
  author: "Bruno Danello",
  sourceName: "GitHub Changelog",
  sourceUrl: "https://github.blog/changelog/2026-10-01-github-copilot-can-now-interact-with-desktop-apps-with-computer-use/",
  date: "2026-10-01",
  content: `
    <p>O GitHub anunciou nesta quinta-feira (1º) que o recurso "computer use" do GitHub Copilot entrou em pré-lançamento público (public preview) para macOS e Windows, tanto no aplicativo de desktop quanto na linha de comando (CLI). Com ele, o Copilot deixa de responder apenas a comandos de código e passa a interagir diretamente com aplicativos de desktop: lê o conteúdo visual e de acessibilidade da tela, clica em botões, digita e edita texto, pressiona teclas, rola páginas, arrasta elementos e navega entre telas de um fluxo de trabalho inteiro.</p>
    <p>Segundo o changelog oficial do GitHub, o objetivo é ampliar o tipo de tarefa que o Copilot consegue automatizar para além de editores de código, alcançando softwares legados ou somente visuais que não oferecem API, linha de comando ou integração via MCP (Model Context Protocol). Na prática, isso inclui sistemas internos antigos de empresas, ferramentas de desktop sem suporte a automação programática e aplicativos que só podem ser operados clicando na interface, cenário comum em áreas como contabilidade, jurídico e operações.</p>

    <h2>Como funciona o controle do computador</h2>
    <p>O recurso vem desativado por padrão: é preciso habilitá-lo manualmente antes que o Copilot ganhe qualquer permissão para interagir com aplicativos de desktop. Mesmo depois de ativado, o controle é condicionado a aprovação explícita por aplicativo: o Copilot pede autorização antes de assumir o controle de um programa específico, e o usuário pode revisar ou revogar a qualquer momento a lista de aplicativos que já permitiu de forma permanente. Esse desenho de permissões segue o mesmo caminho adotado por outras ferramentas de "uso de computador" lançadas ao longo do ano, caso do recurso equivalente que a própria Microsoft colocou em pré-lançamento no Copilot Studio, e reflete uma preocupação crescente do setor com o risco de um agente autônomo tomar ações indesejadas num computador real sem supervisão.</p>
    <p>A chegada do computer use ao Copilot acontece num momento em que a corrida por agentes capazes de operar interfaces gráficas se intensificou: a OpenAI testa recursos parecidos em seus agentes mais recentes, e a Anthropic já havia introduzido uma capacidade similar no Claude meses atrás. O GitHub também vem expandindo rapidamente o escopo do Copilot em 2026, incluindo o lançamento de <a href="/noticias/openai-codex-ambientes-nuvem-revisao-codigo-devday">ambientes de nuvem para revisão de código concorrentes do Codex da OpenAI</a>, e vem reforçando controles de segurança depois que uma falha batizada de <a href="/noticias/plugin4shell-falha-agentes-ia-codigo-claude-code-codex-copilot-gemini">Plugin4Shell expôs diversos agentes de IA para programação a invasão remota</a>, o próprio Copilot entre eles.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem trabalha automatizando tarefas repetitivas ou presta serviço de automação para pequenas empresas no Brasil, o computer use do Copilot abre uma porta que antes dependia de ferramentas de RPA (automação robótica de processos) separadas e caras: agora um assistente de IA já presente no fluxo de programação consegue operar qualquer programa de tela, sem precisar de integração técnica prévia. Isso é especialmente relevante para quem monta soluções sob demanda, como já exploramos em <a href="/artigos/automacao-com-ia-economize-horas-de-trabalho">automação com IA para economizar horas de trabalho</a>: tarefas que antes exigiam gravação de macro ou scripts de RPA complexos passam a ser descritas em linguagem natural ao Copilot.</p>
    <p>Por outro lado, dar a um agente de IA controle direto sobre cliques e digitação num computador de trabalho levanta risco real de erro ou uso indevido, principalmente em máquinas com acesso a sistemas financeiros, dados de clientes ou credenciais sensíveis. Antes de habilitar o recurso em qualquer ambiente de produção, vale aplicar o mesmo cuidado que recomendamos em <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">como escolher uma ferramenta de IA com segurança</a>: testar primeiro numa máquina isolada, revisar com atenção cada aplicativo autorizado e nunca liberar acesso a sistemas que movimentam dinheiro ou dados pessoais sem supervisão humana constante.</p>

    <h2>O que esperar da corrida por agentes que operam a tela</h2>
    <p>O lançamento do GitHub é um sinal de que "computer use" deixou de ser recurso exclusivo de laboratórios de pesquisa e está se tornando item padrão em ferramentas de produtividade usadas por milhões de desenvolvedores. A tendência deve se espalhar para outras suítes de produtividade ao longo dos próximos meses, inclusive fora do universo de programação, seguindo o movimento que já víamos quando comentamos sobre <a href="/artigos/agente-de-ia-chatbot-ou-automacao-qual-a-diferenca">a diferença entre agente de IA, chatbot e automação</a>: a linha entre "assistente que responde perguntas" e "agente que executa tarefas sozinho" continua ficando mais fina.</p>
    <p>Para empresas que já usam Copilot em equipes de desenvolvimento, o recurso ainda está em pré-lançamento, o que significa que pode mudar de comportamento, ganhar novas restrições de segurança ou até ser pausado temporariamente caso surjam problemas durante os testes públicos, como já aconteceu com recursos parecidos em outras empresas de IA ao longo do ano. Vale acompanhar o changelog oficial do GitHub antes de liberar o recurso para toda a equipe, e principalmente antes de conectar o Copilot a qualquer sistema que não tenha um ambiente de testes separado do ambiente real de produção.</p>

    <h3>Diferença entre computer use e automação tradicional</h3>
    <p>Quem já usou ferramentas de RPA tradicionais sabe que elas dependem de um roteiro fixo: gravar os cliques uma vez e repetir exatamente os mesmos passos depois, o que quebra assim que a interface do programa muda um pixel de lugar. O computer use do Copilot funciona de um jeito diferente, porque o modelo de IA por trás dele interpreta a tela em tempo real a cada passo, como faria uma pessoa olhando o programa pela primeira vez. Isso significa que o agente consegue se adaptar quando um botão muda de posição, uma janela de confirmação aparece sem aviso ou um menu é reorganizado, o que reduz a manutenção constante que ferramentas de automação clássica exigem. Em compensação, essa flexibilidade também torna o comportamento do agente menos previsível do que um script fixo, daí a importância dos controles de aprovação por aplicativo que o GitHub colocou como padrão.</p>

    <div class="callout-box">
      <span class="callout-label">Para quem decide testar primeiro</span>
      <p>Antes de ativar o computer use numa conta de trabalho, vale separar uma máquina ou perfil de usuário só para testes, sem acesso a sistemas financeiros, e-mail corporativo ou ferramentas de gestão de clientes. Depois de confirmar que o Copilot se comporta como esperado em tarefas simples e repetitivas, a liberação para aplicativos mais sensíveis deve ser gradual, sempre revisando a lista de programas autorizados antes de ampliar o acesso.</p>
    </div>
  `,
};
