import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "golpes-ia-verizon-dbir-2026",
  title: "Relatório da Verizon mostra IA acelerando golpes e phishing",
  summary:
    "DBIR 2026 analisou 31 mil incidentes em 145 países e mostra phishing e engenharia social turbinados por IA generativa, com SMS e ligações convencendo 40% mais vítimas.",
  author: "Bruno Danello",
  sourceName: "CartaCapital",
  sourceUrl: "https://www.cartacapital.com.br/tecnologia/ia-amplia-arsenal-de-golpes-e-acende-alerta-para-empresas/",
  date: "2026-09-30",
  content: `
    <p>A Verizon divulgou a edição 2026 do Data Breach Investigations Report (DBIR), um dos levantamentos mais citados globalmente sobre segurança digital, e o relatório confirma o que especialistas em cibersegurança vêm alertando há meses: a inteligência artificial generativa está tornando golpes e ataques de phishing mais baratos de produzir e mais difíceis de identificar. Segundo reportagem da <a href="https://www.cartacapital.com.br/tecnologia/ia-amplia-arsenal-de-golpes-e-acende-alerta-para-empresas/" target="_blank" rel="noopener noreferrer nofollow">CartaCapital</a> publicada nesta terça-feira, o estudo analisou 31 mil incidentes de segurança registrados em 145 países ao longo de 2025, dos quais 22 mil resultaram em violações de dados confirmadas.</p>

    <p>O dado que mais chama atenção é o uso de engenharia social por voz e SMS: segundo o DBIR, abordagens feitas por ligação telefônica ou mensagem de texto têm taxa de engajamento das vítimas 40% maior do que tentativas por e-mail, justamente o canal em que ferramentas de clonagem de voz e geração de texto por IA mais evoluíram nos últimos dois anos. A exploração de vulnerabilidades técnicas liderou as causas de violação, respondendo por 31% dos casos, seguida de phishing, com 16%, e de "pretexting" (quando o criminoso finge ser um funcionário de banco, de suporte técnico ou outra figura de confiança) presente em 6% das violações analisadas.</p>

    <h2>Um retrato consistente com o que já se via no Brasil</h2>
    <p>O DBIR da Verizon é global, mas os números batem com uma tendência que o Portal da AI já vinha acompanhando no mercado brasileiro. Em maio, o banco italiano Fideuram perdeu cerca de € 95 milhões em uma fraude que usou <a href="/noticias/golpe-voz-ia-banco-italiano-fideuram-95-milhoes">clonagem de voz por IA para autorizar transferências</a> se passando por um executivo da própria instituição, um caso que mostrou como a tecnologia já havia saído do campo teórico para causar prejuízo financeiro real em instituições grandes e com controles de segurança robustos. No Brasil, o Sindicato dos Trabalhadores em Processamento de Dados (Sindpd) também chamou atenção nesta semana para a dificuldade crescente de identificar golpes com IA, reforçando que o problema não é restrito a bancos europeus.</p>
    <p>Parte da explicação está na própria evolução das ferramentas de voz sintética. A ElevenLabs, uma das líderes do setor, lançou em setembro a quarta geração do seu modelo de clonagem de voz, <a href="/noticias/elevenlabs-lanca-v4-clonagem-voz-90-idiomas">compatível com mais de 90 idiomas e com qualidade quase indistinguível da voz humana</a>. O mesmo tipo de avanço técnico que permite dublagem automática, audiobooks e atendimento por voz mais natural também baixa a barreira técnica para golpistas produzirem áudios falsos convincentes de qualquer pessoa, bastando alguns segundos de gravação real como referência.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você usa IA para trabalhar, vender ou administrar um negócio, o relatório da Verizon é um lembrete prático de que a mesma tecnologia que acelera sua produtividade também acelera o golpista do outro lado da linha. O salto de 40% na eficácia de ligações e SMS em relação a e-mail é especialmente relevante para quem atende clientes por WhatsApp ou telefone: um áudio ou ligação "do banco", "do fornecedor" ou até "do chefe" pedindo uma transferência urgente merece hoje o mesmo nível de desconfiança que um e-mail suspeito já recebia há alguns anos. Nosso <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">checklist de como escolher ferramentas de IA com segurança</a> traz critérios práticos para avaliar esse tipo de risco antes de conectar contas ou dar acesso amplo a qualquer automação.</p>
    <p>Vale lembrar também que esse não é um problema isolado das ferramentas de voz. A própria Anthropic, em seu <a href="/noticias/anthropic-relatorio-uso-indevido-ia-setembro-2026">relatório de uso indevido do Claude divulgado em setembro</a>, já havia documentado casos de golpes e fraudes financeiras facilitados por modelos de linguagem, e a Comissão Federal de Comércio dos Estados Unidos (FTC) abriu nesta terça <a href="/noticias/ftc-investiga-openai-anthropic-agentes-ia">uma investigação sobre os riscos que agentes de IA representam para consumidores</a>, incluindo justamente o potencial de uso indevido em fraudes. O padrão que emerge de fontes tão diferentes (Verizon, Anthropic, reguladores americanos) é o mesmo: a mesma capacidade que torna a IA útil para automatizar tarefas legítimas também reduz o custo e o esforço necessários para golpes em escala.</p>

    <h2>O que fazer na prática para se proteger</h2>
    <p>Especialistas ouvidos pela reportagem recomendam um conjunto de práticas que vale adotar tanto em casa quanto no trabalho. A primeira é estabelecer uma "palavra-chave" combinada previamente com familiares ou colegas de confiança, para confirmar identidade em pedidos urgentes por telefone ou mensagem de voz, já que uma ligação pode soar exatamente como a voz real de alguém conhecido. A segunda é desconfiar de qualquer pedido de transferência, pagamento ou compartilhamento de dados que crie senso de urgência artificial, um gatilho psicológico clássico de engenharia social que a IA apenas tornou mais barato de escalar. A terceira, mais voltada a empresas, é revisar processos internos de autorização financeira para exigir confirmação por mais de um canal antes de qualquer transferência acima de determinado valor, prática que teria evitado boa parte do prejuízo no caso do Fideuram.</p>
    <p>Para quem administra pequenos negócios e usa atendimento automatizado por IA, o relatório também é um alerta sobre o outro lado da moeda: golpistas estão mirando justamente empresas que adotaram canais digitais sem revisar a segurança desses fluxos, explorando a confiança que clientes depositam em mensagens automáticas. O nosso guia sobre <a href="/artigos/ia-e-privacidade-o-que-voce-entrega-sem-perceber">o que você entrega sem perceber ao usar IA</a> detalha, com exemplos práticos, que tipo de dado cada ferramenta conectada a contas reais realmente expõe, e é um bom ponto de partida antes de automatizar qualquer etapa que envolva dinheiro ou dados sensíveis de clientes. Combinar essas duas frentes, ferramentas de IA bem configuradas de um lado e processos de verificação humana reforçados do outro, é hoje o caminho mais realista para reduzir a exposição a esse tipo de golpe sem abrir mão dos ganhos reais de produtividade que a tecnologia oferece.</p>
  `,
};
