import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "google-antigravity-claude-opus-sonnet-5-5-pro-ultra",
  title: "Google adiciona Claude Opus e Sonnet 5.5 ao Antigravity só para Pro/Ultra",
  summary:
    "Google passou a oferecer Claude Opus 5.5 e Sonnet 5.5 no Antigravity, mas só para assinantes Pro e Ultra pagos; Claude 4.6 sai de cena em 2 de novembro.",
  author: "Bruno Danello",
  sourceName: "Google Antigravity",
  sourceUrl: "https://antigravity.google/docs/models",
  date: "2026-10-05",
  content: `
    <p>O Google passou a oferecer os modelos Claude Opus 5.5 e Claude Sonnet 5.5, da Anthropic, dentro do Antigravity, seu ambiente de desenvolvimento voltado para IA agêntica, mas com uma restrição importante: o acesso vale só para assinantes pagos dos planos Google AI Pro (sem ser período de teste) e Google AI Ultra. Segundo a <a href="https://antigravity.google/docs/models" target="_blank" rel="noopener noreferrer nofollow">própria página de documentação de modelos do Antigravity</a>, as versões "thinking" de Opus 5.5 e Sonnet 5.5 passaram a aparecer no menu de seleção de modelos da ferramenta em outubro, sem anúncio oficial em blog, sentido notado primeiro por usuários que acompanham de perto as atualizações do produto.</p>

    <p>A mudança chama atenção porque coloca modelos da concorrente direta Anthropic dentro de uma ferramenta de desenvolvimento construída e mantida pelo próprio Google, ao lado da família Gemini. Quem usa os planos gratuitos, Google AI Plus ou mesmo contas Enterprise fica de fora: a documentação deixa claro que mesmo uma assinatura Pro em período de avaliação gratuita não libera os novos modelos da Anthropic, só a versão paga e recorrente do plano.</p>

    <h2>Claude dentro da casa do concorrente</h2>
    <p>O Antigravity é a aposta do Google para competir no mercado de editores e ambientes de codificação com IA agêntica, um espaço que também inclui ferramentas como o Codex da OpenAI e o próprio Claude Code da Anthropic. Oferecer os modelos da Anthropic dentro da própria plataforma é uma escolha que lembra o movimento já visto em outros lugares do ecossistema: a Microsoft, por exemplo, também passou a <a href="/noticias/mercado-paralelo-claude-china-revenda-tokens">disputar espaço no mercado de tokens de IA</a> de formas que misturam parceria e concorrência entre as mesmas gigantes de tecnologia. Para o usuário final, a vantagem é clara: comparar modelos rivais lado a lado dentro da mesma ferramenta, sem precisar migrar de ambiente ou pagar assinaturas separadas para cada fornecedor.</p>
    <p>A chegada dos modelos 5.5 também sinaliza o fim de uma geração anterior: segundo a documentação, as versões Claude Opus 4.6 e Sonnet 4.6, hoje ainda disponíveis em planos gratuitos e Pro dentro do Antigravity, serão removidas em 2 de novembro de 2026. Quem já usa essas versões mais antigas no dia a dia precisa migrar para os modelos novos (restritos aos planos pagos) ou passar a depender só da família Gemini, que continua disponível em todos os níveis de assinatura, incluindo Gemini 3.8, 3.7 e 3.6 Flash e o Gemini 3.1 Pro.</p>

    <h2>Por que isso importa para quem programa ou gerencia equipe técnica no Brasil</h2>
    <p>Para desenvolvedores brasileiros que já usam Antigravity ou avaliam adotar a ferramenta, a notícia tem um recado direto: o acesso aos modelos mais avançados de raciocínio da Anthropic dentro da plataforma do Google agora depende de pagar a assinatura Pro ou Ultra completa, não dá mais para contar com um período de teste gratuito para avaliar o Opus 5.5 ou o Sonnet 5.5 nesse ambiente específico. Isso é relevante para quem compara ferramentas antes de decidir onde investir o orçamento de IA da equipe, um exercício que já tratamos no guia sobre <a href="/artigos/chatgpt-claude-gemini-qual-ia-escolher">como escolher entre ChatGPT, Claude e Gemini</a> e que agora ganha mais uma camada: a mesma Anthropic por trás do Claude também aparece embutida dentro de produtos de concorrentes diretos, como o próprio Antigravity do Google e, antes dele, o Copilot da Microsoft.</p>
    <p>Vale lembrar que o Sonnet 5.5, quando lançado diretamente pela Anthropic, já chegou com <a href="/noticias/anthropic-lanca-claude-opus-5-5-mais-barato-rapido">preço mais baixo e desempenho melhorado em relação à geração anterior</a>, parte da estratégia da empresa de baratear o acesso aos próprios modelos de ponta antes de uma eventual oferta pública de ações. Ter esses modelos embutidos em mais plataformas, mesmo que só para assinantes pagos, tende a ampliar o alcance deles entre equipes de desenvolvimento que já usam o ecossistema Google Cloud e preferem não gerenciar contratos separados com cada fornecedor de IA.</p>

    <h2>O que muda na prática e o que observar</h2>
    <p>Equipes de desenvolvimento que dependem do Antigravity no dia a dia devem revisar os próprios planos de assinatura antes de 2 de novembro, data em que os modelos Claude 4.6 e o modelo aberto GPT-OSS-120B saem de circulação na ferramenta. Quem está nos planos gratuitos ou Plus e quer manter acesso a modelos de ponta da Anthropic dentro do Antigravity vai precisar decidir entre fazer upgrade para o plano Pro pago (US$ 19,99 por mês) ou Ultra (a partir de US$ 99,99 por mês), ou migrar o fluxo de trabalho para depender só do Gemini, que segue disponível em todos os níveis.</p>
    <p>Também vale acompanhar se o movimento se repete em outras ferramentas de desenvolvimento do próprio Google, como o Gemini CLI, e se a Anthropic mantém essa mesma política de distribuição cruzada em novos lançamentos, oferecendo seus modelos dentro de produtos de concorrentes como parte de uma estratégia mais ampla de ganhar participação de mercado antes da abertura de capital da empresa. Para quem usa ferramentas de código aberto como alternativa, o tema de como essas mudanças afetam o ecossistema já foi tratado no guia sobre <a href="/artigos/ia-codigo-aberto-o-que-muda-para-quem-usa">IA de código aberto e o que muda para quem usa a tecnologia</a>.</p>

    <h2>Um padrão que já se repete entre as gigantes de IA</h2>
    <p>Esse tipo de acordo cruzado entre concorrentes diretos deixou de ser exceção no mercado de IA. Enquanto o Google abre espaço para o Claude dentro do Antigravity, a própria Anthropic também distribui seus modelos através da plataforma de nuvem do Google, o Vertex AI, numa relação comercial que mistura competição e dependência mútua ao mesmo tempo. Esse tipo de arranjo ajuda a explicar por que notícias sobre bastidores da indústria, como as que mostramos sobre a <a href="/noticias/mercado-paralelo-claude-china-revenda-tokens">revenda paralela de tokens do Claude na China</a>, continuam aparecendo com frequência: cada laboratório de IA tenta maximizar a própria receita e distribuição, mesmo que isso signifique colocar o próprio produto dentro da casa de um rival direto.</p>
    <p>Para equipes de tecnologia brasileiras que seguem de perto esse mercado, o episódio reforça uma lição prática: vale sempre revisar a letra fina de qual plano de assinatura realmente dá acesso a quais modelos antes de montar um fluxo de trabalho em torno de uma ferramenta específica. Restrições como a que o Google aplicou ao Opus 5.5 e ao Sonnet 5.5, reservando os modelos mais avançados só para assinantes pagos e excluindo períodos de teste gratuito, tendem a se tornar cada vez mais comuns à medida que o custo de rodar esses modelos de ponta continua alto para as próprias empresas que os oferecem.</p>
  `,
};
