import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "google-gemini-4-argon-lancamento-preco",
  title: "Google lança Gemini 4 Argon, modelo de fronteira focado em código",
  summary:
    "O novo modelo de fronteira do Google custa US$ 2 por milhão de tokens de entrada e US$ 10 de saída, lidera benchmarks de código e cibersegurança, e chega primeiro a defensores cibernéticos.",
  author: "Bruno Danello",
  sourceName: "Google (The Keyword)",
  sourceUrl: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-4-argon/",
  date: "2026-09-30",
  content: `
    <p>O Google anunciou nesta quarta-feira (30) o Gemini 4 Argon, seu novo modelo de fronteira, focado em código, trabalho corporativo de longo prazo e defesa cibernética. Segundo o <a href="https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-4-argon/" rel="noopener noreferrer nofollow">anúncio oficial</a>, assinado por Koray Kavukcuoglu, chefe do Google DeepMind, o modelo já está em uso interno no Google e começa a rodar, por enquanto, apenas para um grupo de "defensores cibernéticos de confiança" dentro do Fairwind Program, o programa de acesso antecipado a ferramentas de cibersegurança da empresa.</p>
    <p>O preço de lançamento é de US$ 2 por milhão de tokens de entrada e US$ 10 por milhão de tokens de saída, com tokens de entrada em cache saindo 95% mais baratos. Depois do período promocional, o valor sobe para US$ 4 e US$ 20 por milhão de tokens, respectivamente. O destaque técnico é o limite de saída de 1 milhão de tokens, saltando dos 64 mil tokens do modelo anterior, o que permite ao Argon raciocinar e gerar uma resposta muito mais longa em uma única tarefa complexa, sem precisar dividir o trabalho em várias chamadas.</p>

    <h2>Um lançamento cauteloso, em meio à corrida entre laboratórios</h2>
    <p>O Gemini 4 Argon chega em um momento de disputa acirrada entre os grandes laboratórios de IA. Poucos dias antes, a <a href="/noticias/openai-lanca-dots-agentes-sempre-ativos-gpt-6-1-sol">OpenAI lançou o GPT-6.1 Sol no DevDay</a>, depois de cancelar o GPT-6.1 Astra por falha de segurança, e a Anthropic segue avançando com o <a href="/noticias/anthropic-lanca-claude-opus-5-5-mais-barato-rapido">Claude Opus 5.5</a>. O Google já havia sinalizado que o Gemini 4 estava em desenvolvimento acelerado: semanas atrás, Kavukcuoglu disse publicamente que o modelo tinha entrado em pós-treinamento e que a empresa queria lançar uma versão antecipada "o quanto antes", como mostramos em nossa cobertura da época. O Argon é essa versão antecipada, embora o Google tenha deixado claro que o lançamento ao público em geral, incluindo assinantes do Gemini 3 no dia a dia, ainda vai demorar, e vai começar por clientes de API pagos e assinantes do Google AI Ultra.</p>
    <p>Nos benchmarks divulgados pela empresa, o Argon lidera o Vals Index, que mede impacto econômico em finanças, direito, código e áreas tributárias, e aparece em primeiro lugar no AutomationBench, do Zapier, que avalia execução de tarefas de negócio de ponta a ponta, com 51,3% de acerto. Em programação, o modelo marca 77,9% no DeepSWE v1.1, referência para tarefas de engenharia de software de longo prazo, e empata em primeiro lugar no CWE-bench v1, que mede a capacidade de corrigir vulnerabilidades de segurança, com 68%. Internamente, o Google já usa agentes do Argon para migrar código de C/C++ para Rust em projetos como o kernel Zircon do Fuchsia, com mais de 800 mil linhas, e diz ter liberado centenas de terabytes de memória em data centers ao aplicar otimizações encontradas pelo próprio modelo.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você usa IA para programar, revisar contratos ou analisar planilhas financeiras no trabalho, o Argon é mais um sinal de que o limite de tokens deixou de ser o maior gargalo desses modelos: com 1 milhão de tokens de saída, tarefas que hoje exigem quebrar um pedido em várias partes (por exemplo, revisar um contrato inteiro ou migrar um sistema grande de código) tendem a caber em uma única resposta. Isso ainda não chegou ao Gemini que você usa hoje no app ou no Workspace, mas costuma ser questão de semanas até um modelo de fronteira como esse virar o padrão nos produtos de consumo do Google, como já aconteceu com o <a href="/artigos/gemini-3-vale-a-pena-novidades-precos-comparacao-chatgpt">Gemini 3</a>.</p>
    <p>Para quem presta serviço de desenvolvimento ou consultoria em IA para clientes no Brasil, vale acompanhar de perto o uso do Argon em cibersegurança: o Google liberou o modelo sem as "grades de proteção" cibernéticas padrão para defensores de confiança, para que eles consigam usar a capacidade máxima do modelo em encontrar e corrigir vulnerabilidades antes que criminosos façam o mesmo. Isso reforça uma tendência que já discutimos no <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">checklist de como escolher ferramenta de IA com segurança</a>: cada vez mais, a capacidade de um modelo em achar falhas de código vira ativo tanto para quem defende quanto para quem ataca sistemas, e o controle de acesso a essas versões "sem grade de proteção" é uma decisão de negócio, não só técnica.</p>

    <h2>O que muda na prática para desenvolvedores</h2>
    <p>O Google diz que o Argon já está "mudando a forma como trabalhamos e construímos" internamente, com times usando o modelo para otimização de algoritmos quânticos e para encontrar e corrigir falhas de código em vinte linguagens de programação diferentes. A empresa de segurança <a href="https://www.wiz.io/scan-for-good" rel="noopener noreferrer nofollow">Wiz</a> já testa o Argon em seu programa Scan for Good, de varredura gratuita de infraestrutura pública crítica, e encontrou com ele uma vulnerabilidade séria em software de saúde usado por hospitais que modelos anteriores não tinham detectado.</p>
    <p>Fica em aberto, por enquanto, quando o Argon chega ao público em geral e se o preço de US$ 2 e US$ 10 por milhão de tokens vai se manter competitivo frente ao GPT-6.1 Sol da OpenAI, que custa o mesmo por token de entrada e saída. Para quem acompanha o mercado de IA para decidir onde investir tempo de aprendizado ou orçamento de API, vale esperar a liberação mais ampla antes de migrar fluxos de trabalho críticos, já que o próprio Google reforça que está testando o modelo com grupos restritos justamente para fechar brechas de segurança antes do lançamento geral.</p>
    <p>Outro ponto que vale acompanhar é o comportamento do Argon em tarefas que envolvem vídeo e imagem: o Google diz que o modelo também se destaca em compreensão visual, com estado da arte no LVBench, benchmark de entendimento de vídeos longos, com 91,7% de acerto. Isso abre espaço para usos que vão além de código, como análise de gráficos financeiros complexos ou leitura automática de uma sequência inteira de documentos digitalizados, tarefa comum em escritórios de contabilidade e departamentos jurídicos que ainda dependem de revisão manual demorada.</p>
  `,
};
