import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "google-gemini-mata-opal-gems-skills",
  title: "Google encerra Opal e Gems no Gemini e aposta tudo em Skills",
  summary:
    "Google confirma fim do Opal e dos Gems personalizados do Gemini até novembro, substituindo os dois por Skills, liberadas a todos os planos pagos.",
  author: "Bruno Danello",
  sourceName: "Google",
  sourceUrl: "https://blog.google/products-and-platforms/products/gemini/automate-tasks-with-skills/",
  date: "2026-09-30",
  content: `
    <p>O Google anunciou nesta semana que vai encerrar o Opal, seu construtor de mini-aplicativos sem código, e descontinuar os Gems, os assistentes personalizados do Gemini, substituindo os dois recursos por um único sistema chamado Skills. Segundo o <a href="https://blog.google/products-and-platforms/products/gemini/automate-tasks-with-skills/" target="_blank" rel="noopener noreferrer nofollow">anúncio oficial no blog do Google</a>, as Skills permitem salvar instruções que se repetem no dia a dia, como redigir relatórios semanais, reescrever textos num tom específico ou resumir PDFs, e rodá-las quantas vezes forem necessárias digitando apenas uma barra ("/") seguida do nome da instrução salva, sem precisar reescrever o prompt inteiro a cada vez.</p>

    <p>A mudança afeta dois públicos diferentes. Donos de Gems, os mini-assistentes que usuários configuravam dentro do Gemini com instruções e arquivos fixos, terão suas criações convertidas automaticamente em Skills quando os Gems forem desativados para contas pessoais, em novembro de 2026. Já quem usava o Opal, ferramenta experimental de criação de mini-aplicativos sem programação hospedada em opal.google.com, não tem o mesmo caminho: o serviço fecha simultaneamente, sem conversão automática dos projetos, e quem quiser manter um fluxo de trabalho criado ali precisa recriá-lo manualmente dentro do novo formato de Skills.</p>

    <h2>Como funcionam as Skills e o que elas resolvem</h2>
    <p>A principal queixa sobre os Gems era a limitação: eles guardavam instruções e um conjunto fixo de arquivos de referência, mas não deixavam combinar várias configurações numa mesma conversa nem anexar múltiplos tipos de documento à vontade. As Skills chegam justamente para cobrir essas lacunas, com suporte a arquivos de referência em texto, PDF e imagem, e a possibilidade de empilhar mais de uma Skill ao mesmo tempo numa única conversa, algo que o Gemini não permitia até então.</p>
    <p>O cronograma de transição é escalonado por tipo de conta. Para usuários pessoais, a criação e edição de novos Gems já havia sido travada a partir de 13 de outubro de 2026, e a extinção definitiva, com conversão automática para Skills, ocorre em novembro deste ano. Contas do Google Workspace para empresas, organizações sem fins lucrativos e setor corporativo têm prazo mais longo, até março de 2027, e contas de instituições de ensino só completam a migração em junho de 2027. O Opal, por sua vez, encerra junto com a primeira leva, em novembro, e os repositórios abertos do projeto no GitHub (Breadboard e Opal ADK) passam a ficar apenas em modo leitura, continuando acessíveis sob suas licenças originais, mas sem receber atualizações.</p>
    <p>Até a semana passada, o acesso a Skills exigia uma assinatura paga do Gemini, mas o próprio anúncio do Google confirma que o recurso passa a estar disponível a todos os níveis pagos de assinatura da IA do Google, com expansão prevista para clientes do Workspace (empresas, organizações sem fins lucrativos e educação) "nas próximas semanas". A dúvida que ainda não foi esclarecida oficialmente é se usuários da versão gratuita do Gemini também vão ganhar acesso às Skills ou se o recurso continuará restrito a quem paga, o que deixaria quem usa só a camada free sem herdeiro direto para os Gems que já tinha configurado.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem já tinha investido tempo configurando Gems no Gemini, seja para rotinas de trabalho, atendimento ou produção de conteúdo, a boa notícia é que a migração promete ser automática: a instrução salva continua existindo, só muda de nome e de formato de acionamento. O ponto de atenção é para quem usa (ou usava) o Opal para montar mini-aplicativos internos sem código, como pequenas ferramentas de triagem, calculadoras personalizadas ou fluxos de aprovação simples: esses projetos não migram sozinhos e precisam ser reconstruídos manualmente em Skills antes do desligamento, sob risco de perder o fluxo de trabalho por completo.</p>
    <p>Esse tipo de troca de peça fundamental num produto de IA que muita gente já usa no trabalho reforça um padrão que o Portal da AI já vem acompanhando: ferramentas de produtividade com IA mudam de nome, de interface e de regra de acesso com uma frequência bem maior do que softwares tradicionais, e quem depende delas no dia a dia profissional precisa ficar de olho nos anúncios oficiais, não só na experiência dentro do produto. Vale a leitura de como funciona hoje o <a href="/artigos/gemini-3-vale-a-pena-novidades-precos-comparacao-chatgpt">Gemini em comparação com o ChatGPT</a> para quem está decidindo onde concentrar fluxos de automação, e também a análise sobre quando vale a pena <a href="/artigos/ia-gratis-ou-paga-o-que-vale-a-pena">pagar por uma assinatura de IA</a>, já que o acesso a recursos como Skills está cada vez mais ligado ao plano pago, não ao produto em si.</p>

    <h2>O que observar daqui para frente</h2>
    <p>Quem monta automações de negócio apoiadas em IA, como as descritas no guia sobre <a href="/artigos/notion-zapier-e-ia-automatize-seu-negocio-sem-programar">automatizar processos sem programar com Notion, Zapier e IA</a>, deve tratar o fim do Opal como um alerta prático: ferramentas experimentais de grandes empresas de tecnologia podem ser descontinuadas com poucos meses de aviso, então vale manter documentação própria de qualquer fluxo criado numa plataforma de terceiros, para não depender só da exportação automática prometida pelo fornecedor.</p>
    <p>Outro ponto a monitorar é se o Google vai estender Skills à camada gratuita do Gemini ou manter o recurso exclusivo de assinantes, decisão que ainda não foi anunciada oficialmente segundo o próprio comunicado da empresa. Enquanto isso não for esclarecido, quem usa a versão gratuita e tinha Gems configurados corre o risco de perder o recurso sem um substituto direto quando a migração automática for concluída em novembro. A tendência mais ampla, de qualquer forma, é a consolidação de assistentes personalizados, automações e mini-aplicativos num único sistema de instruções reutilizáveis, movimento que a <a href="/noticias/perplexity-computer-automations-slack-gmail">Perplexity também vem seguindo com automações recorrentes integradas a Slack e Gmail</a>, e que deve se tornar padrão entre os grandes provedores de IA generativa ao longo dos próximos meses.</p>
  `,
};
