import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "khanna-pesos-modelos-ia-seguranca-china",
  title: "Deputado dos EUA pede a OpenAI e Anthropic dados sobre espionagem chinesa",
  summary:
    "Ro Khanna cobra de OpenAI, Anthropic, Google, Meta e SpaceXAI informações sobre tentativas da China de roubar pesos de modelos de IA.",
  author: "Bruno Danello",
  sourceName: "Reuters",
  sourceUrl:
    "https://www.investing.com/news/stock-market-news/leading-democrat-asks-ai-firms-for-data-on-any-chinese-access-to-sensitive-code-4926789",
  date: "2026-10-01",
  content: `
    <p>O deputado democrata Ro Khanna, que representa parte do Vale do Silício e é o membro de maior hierarquia do Comitê Seleto da Câmara dos EUA sobre a China, enviou nesta quinta-feira, 1º de outubro de 2026, cartas formais aos presidentes executivos da OpenAI, Anthropic, Google, Meta e SpaceXAI pedindo dados sobre qualquer tentativa, conhecida pelas empresas, de a China ou outros atores hostis acessarem ilegalmente os pesos de seus modelos de inteligência artificial. Segundo apuração da <a href="https://www.investing.com/news/stock-market-news/leading-democrat-asks-ai-firms-for-data-on-any-chinese-access-to-sensitive-code-4926789" target="_blank" rel="noopener noreferrer nofollow">Reuters</a>, Khanna também exigiu detalhes sobre as medidas de cibersegurança que cada empresa já implementou para impedir esse tipo de roubo.</p>

    <p>Pesos de modelo são os parâmetros numéricos resultantes do treinamento de uma IA, o equivalente ao "cérebro" de um sistema como o GPT ou o Claude depois de meses de treinamento com custo de centenas de milhões de dólares. Nas cartas, Khanna argumentou que o roubo de um modelo de fronteira por um ator estatal hostil representaria um risco direto à segurança nacional e à vantagem competitiva dos Estados Unidos na corrida da IA, chegando a afirmar que "o roubo dos pesos de um modelo avançado por um ator não estatal hostil poderia colocar em risco toda a humanidade".</p>

    <h2>Um pedido que chega em meio a tensão crescente entre EUA e China na IA</h2>
    <p>A cobrança de Khanna não surge isolada. Ela acontece poucos dias depois de a <a href="/noticias/eua-china-acordo-dialogo-ia-cupula-trump-xi">cúpula entre Trump e Xi Jinping ter resultado numa trégua comercial</a> que incluiu parte da pauta de inteligência artificial, e num momento em que empresas chinesas de IA, como a DeepSeek, vêm sendo acusadas publicamente por OpenAI e Anthropic de usar uma técnica chamada "destilação": treinar seus próprios modelos usando as respostas geradas por sistemas ocidentais mais avançados, numa espécie de cópia indireta do conhecimento acumulado sem acesso aos pesos originais. A DeepSeek, aliás, segue avançando de forma independente, como mostrou a notícia sobre a empresa chinesa que <a href="/noticias/deepseek-abre-codigo-ferramentas-chips-huawei">abriu o código de ferramentas para chips da Huawei</a> e também a cobertura sobre o crescimento de receita da companhia antes de uma possível oferta pública em Xangai.</p>
    <p>Na frase mais citada da carta, Khanna resumiu o tamanho do risco ao declarar que "nunca antes a segurança nacional e as perspectivas econômicas de uma nação dependeram tanto da cibersegurança de um pequeno punhado de empresas". O pedido chega na mesma semana em que a Federal Trade Commission (FTC) dos EUA abriu uma <a href="/noticias/ftc-investiga-openai-anthropic-agentes-ia">investigação separada sobre OpenAI e Anthropic ligada a riscos de agentes de IA</a>, o que mostra como o Congresso e os órgãos regulatórios americanos estão mirando as mesmas poucas empresas de IA de fronteira sob ângulos diferentes: segurança do consumidor de um lado, segurança nacional do outro.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem usa, revende ou constrói produtos em cima de modelos de IA no Brasil, esse tipo de pedido formal de um parlamentar americano costuma ser o primeiro sinal público de que regras mais duras de exportação de tecnologia e controle de acesso a modelos de fronteira podem vir a seguir. Historicamente, pedidos de informação como esse antecederam novas exigências de licenciamento e restrições de acesso a chips e modelos, o que pode afetar o custo e a disponibilidade de ferramentas de IA usadas por empresas brasileiras que dependem de APIs da OpenAI, Anthropic e Google.</p>
    <p>Também vale observar o outro lado da moeda: a pressão por segurança mais rígida nos modelos ocidentais de fronteira tende a reforçar o apelo comercial de alternativas chinesas de código aberto, como o Xiaomi MiMo ou os modelos da DeepSeek, que seguem ganhando espaço em desenvolvedores de fora dos EUA justamente por terem menos barreiras de acesso. Quem decide qual ferramenta de IA usar no trabalho ou no próprio negócio deve acompanhar esse tipo de notícia junto com o guia sobre <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">como escolher uma ferramenta de IA com segurança</a>, já que critérios como onde os dados são processados e quem tem acesso aos modelos tendem a pesar cada vez mais nessa escolha.</p>

    <h2>O que observar nos próximos meses</h2>
    <p>Khanna não tem poder de forçar as empresas a responder, já que cartas de parlamentares individuais funcionam como pedido formal, não como intimação com força de lei, mas esse tipo de movimento costuma preceder audiências públicas no Congresso e projetos de lei mais específicos sobre segurança de modelos de IA, na linha do que já tramita com o <a href="/noticias/sanders-casar-projeto-lei-banir-superinteligencia-ia">projeto de Bernie Sanders e Greg Casar para restringir o desenvolvimento de superinteligência</a> e com o <a href="/noticias/senadores-eua-projeto-lei-transparencia-ia-systems-transparency-act">projeto bipartidário que exige mais transparência das empresas de IA</a>. As respostas das cinco empresas à carta de Khanna, se tornadas públicas, devem servir de termômetro de quão exposto cada uma delas já está a tentativas reais de espionagem industrial chinesa, informação que hoje fica quase inteiramente dentro das próprias companhias.</p>
    <p>Vale lembrar que OpenAI e Anthropic já relataram publicamente, em relatórios anteriores de segurança, terem identificado contas ligadas a grupos chineses usando seus produtos para tarefas associadas a operações de vigilância e desenvolvimento de software ofensivo, o que reforça que a preocupação de Khanna não é hipotética. Caso alguma das cinco empresas confirme uma tentativa concreta de roubo de pesos de modelo, é provável que o episódio reabasteça o debate sobre controles de exportação de tecnologia de IA que já circula em Washington desde que restrições a chips avançados da Nvidia para a China entraram em vigor, e que pode voltar a pressionar o mercado brasileiro de nuvem e infraestrutura de IA, hoje dependente majoritariamente de fornecedores americanos.</p>

    <div class="callout-box">
      <span class="callout-label">Para entender melhor</span>
      <p>"Pesos de modelo" (model weights, em inglês) são os números que definem como uma rede neural de IA processa informação depois de treinada, algo como milhões ou bilhões de parâmetros ajustados durante meses de treinamento com GPUs caríssimas. Quem tem acesso aos pesos de um modelo como o GPT ou o Claude pode, em teoria, rodá-lo em seus próprios servidores sem pagar pela API ou seguir as regras de uso impostas pelo criador original, o que torna esse arquivo um dos ativos mais valiosos e mais vigiados de qualquer empresa de IA de fronteira.</p>
    </div>
  `,
};
