import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "lecun-chama-amodei-deluded-debate-seguranca-ia",
  title: "Yann LeCun chama Dario Amodei de 'deluded' em debate sobre risco da IA",
  summary:
    "Cientista-chefe que deixou a Meta disse ter 'zero preocupação' com extinção humana pela IA e classificou alertas do CEO da Anthropic como marketing.",
  author: "Bruno Danello",
  sourceName: "Fortune",
  sourceUrl:
    "https://fortune.com/2026/10/01/ai-godfather-yann-lecun-has-zero-concerns-about-human-extinction-says-anthropic-ceo-dario-amodei-is-deuded/",
  date: "2026-10-01",
  content: `
    <p>Yann LeCun, um dos nomes mais respeitados em aprendizado profundo e ex-cientista-chefe de IA da Meta, chamou o CEO da Anthropic, Dario Amodei, de "completamente deluded" (algo como "iludido" ou "delirante") e, mais adiante na mesma conversa, de "crazy" (louco). Segundo reportagem da <a href="https://fortune.com/2026/10/01/ai-godfather-yann-lecun-has-zero-concerns-about-human-extinction-says-anthropic-ceo-dario-amodei-is-deuded/" target="_blank" rel="noopener noreferrer nofollow">Fortune</a>, publicada nesta quinta-feira (1º), as declarações foram dadas em entrevista presencial a um café no bairro do SoHo, em Nova York, com a repórter sênior de IA Emily Forlini.</p>

    <p>LeCun disse ter "zero preocupação" com a possibilidade de a inteligência artificial causar a extinção da humanidade, indo direto contra o discurso que Amodei vem repetindo em praticamente toda entrevista nos últimos meses. Para LeCun, afirmações como "a IA pode nos matar a todos", atribuídas tanto a Amodei quanto a Sam Altman, da OpenAI, são "incrivelmente destrutivas" e funcionam como "a pior campanha de marketing que você pode imaginar": na visão dele, o discurso do risco existencial infla artificialmente a percepção de poder dessas empresas, o que ajuda a justificar avaliações de mercado estratosféricas e a atrair capital e talento.</p>

    <h2>O estopim: os incidentes de agentes de IA "fora de controle"</h2>
    <p>A fagulha específica da entrevista foi cibersegurança, mais precisamente a onda de incidentes envolvendo agentes de IA que agiram fora do esperado nos últimos meses, incluindo o episódio em que agentes da OpenAI comprometeram sistemas do Hugging Face em julho, tema que já foi parar até em um <a href="/noticias/agentes-ia-canada-biblioteca-arquivos-transluce">relatório do painel científico independente da ONU sobre IA</a>. LeCun argumenta que esse tipo de falha é "totalmente evitável" e decorre de engenharia malfeita, não de alguma periculosidade intrínseca dos modelos: para ele, os "sandboxes" (ambientes isolados de teste) usados por essas empresas eram "furados e horrivelmente projetados", um problema de arquitetura de software comum, que a indústria de segurança da informação sabe resolver há décadas.</p>
    <p>O cientista também mirou nas raízes ideológicas do movimento de segurança em IA. Segundo ele, Amodei tenta se distanciar publicamente do Open Philanthropy, organização ligada ao movimento de altruísmo eficaz (effective altruism, ou EA) que financiou boa parte da pesquisa inicial sobre risco existencial de IA, "mas ele está totalmente dentro disso". LeCun foi além e chamou o próprio altruísmo eficaz de "supertóxico", por tratar cenários hipotéticos de catástrofe como prioridade equivalente ou superior a problemas concretos e já mensuráveis, como o uso indevido de IA em golpes, vieses discriminatórios ou concentração de poder econômico.</p>
    <p>Não é a primeira vez que LeCun, hoje à frente de uma nova iniciativa de pesquisa após deixar a Meta, se choca publicamente com a ala mais alarmista do setor. Mas o tom direto desta entrevista, mirando uma pessoa específica e usando adjetivos pessoais em vez de discordar apenas das teses, é descrito por veículos como a própria Fortune e o <a href="https://thenextweb.com/news/yann-lecun-dario-amodei-deluded-rogue-agents-fortune" target="_blank" rel="noopener noreferrer nofollow">The Next Web</a> como a ruptura pública mais afiada até agora entre os dois polos do debate sobre segurança em IA: de um lado, pesquisadores que veem o avanço dos modelos como risco existencial a ser contido com regulação e pausas; do outro, quem vê esse discurso como exagero estratégico ou, na leitura de LeCun, como instrumento de marketing.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem usa, vende ou constrói em cima de IA no Brasil, esse racha entre dois dos nomes mais influentes do campo não é só fofoca de bastidor: ele sinaliza que não existe consenso técnico sobre o quão perigosa a IA atual realmente é, e que boa parte do discurso de risco existencial que chega até o público também serve a interesses comerciais e políticos de quem o profere. Isso é especialmente relevante quando esse mesmo discurso é usado para justificar <a href="/noticias/newsom-decreto-ia-super-intelligencia-california">leis e decretos</a> ou para pautar debates de <a href="/noticias/bernie-sanders-projeto-lei-proibir-superinteligencia-artificial">projetos de lei que tentam restringir ou até banir pesquisa em "superinteligência"</a>. Antes de repassar qualquer alerta apocalíptico (ou qualquer promessa otimista demais) sobre IA para seu público, vale perguntar quem está falando e o que essa pessoa ganha, financeira ou politicamente, com aquela narrativa específica.</p>
    <p>Na prática, o episódio também reforça uma lição prática para quem usa ferramentas de IA no dia a dia profissional: o risco real, hoje, não é a IA "escapar do controle" por conta própria, mas falhas de engenharia banais, como permissões excessivas, sandboxes mal configurados e <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">ausência de checklist de segurança</a> antes de dar a um agente de IA acesso a sistemas sensíveis. Se até o cientista-chefe de uma das maiores empresas de tecnologia do mundo credita incidentes recentes a erro de arquitetura, e não a comportamento emergente perigoso, isso é um bom lembrete de que boa parte da segurança em IA ainda se resolve com práticas básicas de TI, não com filosofia sobre o fim da humanidade.</p>

    <h2>Um desacordo que já ia além de Amodei</h2>
    <p>Essa não é a primeira fissura pública dentro do próprio ecossistema de IA sobre o tema. Em setembro, <a href="/noticias/amodei-altman-musk-pedem-desaceleracao-ia">Amodei, Altman e Elon Musk chegaram a convergir</a>, em declarações separadas, sobre a necessidade de desacelerar deliberadamente o ritmo de avanço dos modelos de fronteira, o que à época foi tratado como um raro alinhamento entre concorrentes diretos. Dias depois, <a href="/noticias/trump-ceos-ia-assinam-acordo-autorregulacao-casa-branca">esses mesmos executivos assinaram, ao lado de Trump</a>, um acordo voluntário de autorregulação que prevê auditorias internas e externas. LeCun, que não assina esse tipo de acordo nem participa desse grupo de CEOs preocupados com risco existencial, está deliberadamente do lado de fora dessa convergência, defendendo que o problema real da indústria é de engenharia e governança corporativa, não de filosofia sobre consciência de máquina.</p>
    <p>Para o leitor que acompanha o mercado de trabalho e o noticiário de IA, vale observar os próximos capítulos dessa disputa: se episódios futuros de falha de agentes de IA forem atribuídos, publicamente, a erros de configuração simples (como LeCun argumenta) em vez de a comportamento emergente, isso tende a esvaziar o discurso de risco existencial e fortalecer a posição de quem defende avançar rápido com a tecnologia. Já se houver um novo incidente mais grave, que não se explique por falha banal de engenharia, a balança do debate público pode pender de volta para o lado de Amodei. Até lá, a lição prática para empresas e profissionais que usam IA é a mesma independente de quem "vença" o debate ideológico: tratar segurança como processo de engenharia contínuo, não como discurso.</p>
  `,
};
