import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "marco-legal-ia-congresso-trump-xi-descarta-regulacao",
  title: "Sem acordo EUA-China, Congresso tenta destravar Marco Legal da IA",
  summary:
    "Após Trump recusar regras globais com Xi Jinping, Agência Senado mostra como o PL 2.338/2023 e outros dois projetos avançam no Brasil para regular agentes de IA.",
  author: "Bruno Danello",
  sourceName: "Rádio Senado",
  sourceUrl:
    "https://www12.senado.leg.br/radio/1/noticia/2026/10/01/descartada-em-encontro-de-eua-e-china-regulacao-da-ia-e-analisada-no-brasil",
  date: "2026-10-01",
  content: `
    <p>Enquanto Estados Unidos e China encerraram a cúpula de fim de setembro entre Donald Trump e Xi Jinping sem nenhum compromisso conjunto sobre regras para inteligência artificial, o Congresso brasileiro segue tentando destravar sua própria legislação sobre o tema. É o que mostra reportagem publicada em 1º de outubro pela <a href="https://www12.senado.leg.br/radio/1/noticia/2026/10/01/descartada-em-encontro-de-eua-e-china-regulacao-da-ia-e-analisada-no-brasil" target="_blank" rel="noopener noreferrer nofollow">Rádio Senado</a>, agência de notícias oficial do Senado Federal.</p>
    <p>Segundo o texto, Trump recusou qualquer cooperação regulatória internacional com a China durante o <a href="/noticias/trump-xi-cupula-tregua-comercial-chips-ia-jensen-huang-altman">encontro entre os dois líderes na Casa Branca</a>, preferindo deixar o setor de IA avançar sob autorregulação das próprias empresas americanas, enquanto o governo chinês defendeu que a responsabilidade pelos riscos da tecnologia deveria ser compartilhada entre os países que a desenvolvem. Esse impasse global é usado pela Agência Senado como gancho para destacar que, na ausência de um padrão internacional, cabe a cada país decidir suas próprias regras, e que o Brasil tenta justamente isso com o Marco Legal da Inteligência Artificial, o PL 2.338/2023.</p>

    <h2>O que diz o Marco Legal da IA e onde ele está travado</h2>
    <p>O PL 2.338/2023, de autoria do ex-senador Rodrigo Pacheco, foi aprovado pelo Senado em dezembro de 2024 e desde então está parado na Câmara dos Deputados, onde uma comissão especial reúne o projeto original a outras 37 propostas apensadas sobre o tema. A proposta busca, segundo descrição da própria Agência Senado, equilibrar a proteção a direitos fundamentais dos cidadãos com o incentivo à inovação tecnológica, prevendo regras de transparência, classificação de sistemas por nível de risco e responsabilização de empresas que desenvolvem ou operam IA no país. Caso a Câmara aprove o texto com mudanças relevantes, ele ainda precisa voltar ao Senado para nova votação antes de seguir para sanção presidencial, o que torna o calendário de aprovação ainda mais incerto.</p>
    <p>Além do projeto principal, a reportagem cita dois textos mais recentes que tramitam em paralelo: o PL 750/2026, que prevê o uso de inteligência artificial associada a tornozeleiras eletrônicas para monitorar agressores em medidas protetivas da Lei Maria da Penha, defendido pela senadora Daniella Ribeiro (PP-PB), e o PL 846/2026, que cria uma lei de governança de IA especificamente para o setor público, com normas de transparência e auditoria para sistemas usados por órgãos do governo. O senador Flávio Arns (PSB-PR) também é citado defendendo a associação entre inteligência artificial e educação desde o ensino básico, mostrando que a discussão legislativa brasileira não se limita a um projeto só, mas se espalha por frentes setoriais específicas enquanto o texto geral segue sem data para votação.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem usa ferramentas de IA no trabalho ou está construindo um negócio em torno delas no Brasil, a demora na aprovação do Marco Legal tem um efeito direto: segue não existindo uma lei federal específica definindo, por exemplo, que tipo de sistema de IA é considerado de "alto risco", quais obrigações de transparência uma empresa brasileira tem ao usar IA para decisões que afetam clientes (como crédito, contratação ou atendimento), ou que tipo de responsabilidade cabe a quem desenvolve versus quem apenas usa um modelo de terceiros. Isso cria uma zona cinzenta em que empresas de diferentes tamanhos aplicam critérios próprios, o que tende a mudar bastante quando o projeto finalmente for votado na Câmara.</p>
    <p>A ausência de acordo global entre EUA e China citada pela matéria também importa na prática: empresas brasileiras que usam modelos de fronteira como o GPT, o Claude ou o Gemini continuam operando num cenário em que cada bloco de países define suas próprias regras, sem um padrão único que simplifique a conformidade para quem exporta serviços de IA ou atende clientes internacionais. Isso significa que a <a href="/artigos/lei-de-ia-no-brasil-o-que-muda-para-quem-usa">regulação brasileira, quando sair, provavelmente vai conviver com regras diferentes</a> das que já existem na União Europeia (AI Act) e nos Estados Unidos (regras estaduais fragmentadas, já que o <a href="/noticias/newsom-decreto-ia-super-intelligencia-california">governo federal americano também não aprovou um marco único</a>), obrigando empresas brasileiras com operação internacional a navegar múltiplos regimes ao mesmo tempo.</p>

    <h2>O que observar na tramitação daqui para frente</h2>
    <p>Vale acompanhar se a comissão especial da Câmara avança com um relatório final sobre o PL 2.338/2023 ainda em 2026, já que o projeto está nessa fase há quase dois anos sem previsão formal de votação em plenário. A proximidade das eleições de outubro também tende a influenciar o ritmo do Congresso: pautas que dividem opinião e exigem acordo político amplo, caso do Marco Legal da IA, costumam perder prioridade em ano eleitoral, quando parlamentares concentram energia em temas que rendem mais capital político com o eleitorado.</p>
    <p>Outro ponto a observar é se os projetos mais específicos, como o PL 750/2026 (tornozeleiras com IA) e o PL 846/2026 (governança no setor público), avançam mais rápido isoladamente do que o texto geral, o que já aconteceu em outros países: regras setoriais específicas tendem a gerar menos resistência do que uma lei ampla que tenta cobrir toda a cadeia de IA de uma vez. Enquanto isso, iniciativas como o <a href="/noticias/lula-ia-portugues-pbia-plano-nacional">Plano Brasileiro de Inteligência Artificial</a> seguem avançando no Executivo por meio de decretos e programas de investimento, numa dinâmica em que o governo federal consegue atuar sem depender da aprovação do Congresso, enquanto o arcabouço legal que definiria direitos e deveres de quem usa IA no dia a dia continua represado.</p>

    <div class="callout-box"><span class="callout-label">Para lembrar</span>O PL 2.338/2023 (Marco Legal da IA) foi aprovado pelo Senado em dezembro de 2024 e está parado numa comissão especial da Câmara dos Deputados, com 37 propostas apensadas. Em paralelo, tramitam o PL 750/2026 (IA e tornozeleiras eletrônicas na Lei Maria da Penha) e o PL 846/2026 (governança de IA no setor público). A reportagem da Agência Senado conecta a lentidão brasileira à falta de acordo entre EUA e China sobre regras globais de IA na cúpula de Trump e Xi Jinping.</div>
  `,
};
