import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "mckinsey-11-milhoes-trabalhadores-ia-2035",
  title: "McKinsey: IA pode forçar 11 milhões de americanos a trocar de emprego",
  summary:
    "Relatório da McKinsey estima que a IA vai triplicar o ritmo de trabalhadores dos EUA que precisam mudar de ocupação até 2035.",
  author: "Bruno Danello",
  sourceName: "Bloomberg",
  sourceUrl: "https://www.bloomberg.com/news/articles/2026-09-29/ai-may-force-11-million-workers-into-new-jobs-mckinsey-says",
  date: "2026-09-29",
  content: `
    <p>Um relatório do McKinsey Global Institute divulgado nesta terça-feira, 29 de setembro, estima que cerca de 11 milhões de trabalhadores americanos, o equivalente a 7% da força de trabalho atual dos Estados Unidos, podem precisar trocar de ocupação até 2035 por causa do avanço da inteligência artificial. Segundo reportagem da <a href="https://www.bloomberg.com/news/articles/2026-09-29/ai-may-force-11-million-workers-into-new-jobs-mckinsey-says" target="_blank" rel="noopener noreferrer nofollow">Bloomberg</a>, a consultoria calcula que o ritmo anual de trocas de ocupação nos EUA, historicamente em torno de 215 mil pessoas por ano, pode triplicar na próxima década por conta da automação impulsionada por IA.</p>

    <p>O estudo não trata a IA apenas como destruidora de empregos: a McKinsey projeta que a automação pode reduzir a demanda por mão de obra em 36 milhões de postos até 2035, mas que o crescimento de setores ligados a IA e da economia em geral deve gerar demanda equivalente a 40 milhões de vagas no mesmo período. O problema, segundo a consultoria, é que cerca de 25 milhões desses 36 milhões de trabalhadores afetados devem conseguir permanecer na própria ocupação porque o crescimento do próprio setor compensa o impacto da automação. Os outros 11 milhões, porém, precisarão migrar de fato para uma ocupação diferente, e seis em cada sete dessas pessoas enfrentarão necessidade de requalificação significativa e perda de renda no processo.</p>

    <h2>Quem sente o impacto primeiro e por quê</h2>
    <p>O levantamento aponta três áreas como os principais pontos de pressão dentro das empresas: suporte administrativo e de escritório, vendas e varejo, e transporte e logística. São funções com alto volume de tarefas repetitivas e padronizáveis, que hoje já são alvo direto de ferramentas de automação e de agentes de IA capazes de responder e-mails, organizar agendas, atender clientes ou otimizar rotas sozinhos. A McKinsey também chama atenção para uma desigualdade dentro desse processo: trabalhadores de baixa renda têm probabilidade de precisar trocar de ocupação quase oito vezes maior do que trabalhadores de alta renda, o que reforça um padrão já discutido em outros estudos sobre automação, no qual o impacto da tecnologia tende a recair de forma desproporcional sobre quem já está em posição mais vulnerável no mercado de trabalho.</p>
    <p>Esse não é o primeiro sinal desse tipo vindo de grandes consultorias e empresas de tecnologia. A própria OpenAI já divulgou pesquisas próprias sobre <a href="/noticias/openai-pesquisa-trabalhadores-novas-formas-de-trabalhar">como trabalhadores estão reorganizando suas rotinas</a> em torno de ferramentas de IA generativa, e a Oracle chegou a citar explicitamente a IA como motivo para o corte de 21 mil postos em um documento enviado à SEC, a comissão de valores mobiliários dos EUA, no fim de setembro. O que o relatório da McKinsey adiciona é uma tentativa de quantificar, em escala nacional e com metodologia própria, o tamanho da transição que está por vir, em vez de tratar cada anúncio de corte de forma isolada.</p>

    <h2>Por que isso importa para você</h2>
    <p>Mesmo sendo um estudo focado no mercado americano, os números da McKinsey funcionam como um termômetro relevante para quem acompanha o mercado de trabalho no Brasil, porque as mesmas categorias de função citadas no relatório (suporte administrativo, vendas, atendimento, logística) são justamente as mais expostas à automação também por aqui, e tendem a seguir tendências parecidas com alguma defasagem. O dado mais importante para quem trabalha ou lidera equipes hoje não é o número absoluto de 11 milhões, mas o fato de que o grupo mais afetado precisa de requalificação real, não de um curso rápido: são pessoas mudando de ocupação, não só de ferramenta.</p>
    <p>Na prática, isso reforça um conselho que já vale para quem usa IA no dia a dia profissional: não adianta aprender a operar um chatbot e parar por aí. Quem trabalha em funções mais expostas à automação, como as listadas no estudo, ganha mais segurança se já começar a se posicionar em tarefas que combinam julgamento humano, relacionamento e supervisão de sistemas de IA, em vez de competir diretamente com a automação na execução repetitiva. O Portal da AI já tratou desse tema em detalhe no guia sobre <a href="/artigos/empregos-que-a-ia-vai-transformar-como-se-preparar">empregos que a IA vai transformar e como se preparar</a> e no passo a passo de <a href="/artigos/como-se-recolocar-no-mercado-depois-de-ser-substituido-por-automacao">como se recolocar no mercado depois de ser substituído por automação</a>, ambos pensados justamente para esse cenário de transição forçada descrito pela McKinsey.</p>

    <h2>O que observar nos próximos meses</h2>
    <p>Vale acompanhar se empresas brasileiras, públicas e privadas, vão adotar programas de requalificação em escala parecida com o que já começa a aparecer nos EUA, onde algumas grandes companhias anunciaram parcerias com universidades e plataformas de ensino para tentar absorver parte da força de trabalho deslocada internamente, em vez de simplesmente demitir. Outro ponto de atenção é o ritmo real de adoção de agentes de IA dentro das empresas: pesquisas recentes mostram que a maioria das organizações, inclusive no Brasil, ainda está em estágio básico de uso da tecnologia, o que sugere que o processo descrito pela McKinsey deve ser gradual, e não uma ruptura repentina em um único ano. Para quem quer se antecipar, o momento de investir em requalificação e em domínio prático de ferramentas de <a href="/artigos/agentes-de-ia-o-futuro-do-trabalho-autonomo-explicado">agentes de IA</a> é antes da migração se tornar obrigatória, não depois.</p>

    <h2>Como interpretar um número desse tamanho sem exagerar nem minimizar</h2>
    <p>Um erro comum ao ler estudos como o da McKinsey é tratar o número absoluto (11 milhões de pessoas) como se fosse um evento único e catastrófico marcado para um dia específico em 2035. Não é assim que a transição tende a acontecer. O próprio relatório trabalha com uma faixa de incerteza, entre 6 milhões e 16 milhões de trabalhadores, justamente porque o ritmo de adoção da IA nas empresas ainda é imprevisível e depende de fatores como custo de implementação, regulação, resistência cultural dentro das organizações e a própria maturidade das ferramentas disponíveis. Na prática, o que o estudo descreve é um processo contínuo e gradual de substituição de tarefas específicas dentro de cada função, que só se acumula em troca completa de ocupação depois de um período de erosão da demanda pelo trabalho antigo.</p>
    <p>Isso muda a forma como o leitor brasileiro deveria reagir à notícia. Em vez de esperar um corte abrupto que force uma mudança de carreira da noite para o dia, faz mais sentido observar sinais graduais dentro do próprio setor em que se trabalha, como redução de contratações para funções muito repetitivas, aumento da cobrança por habilidades de supervisão e revisão de resultados de IA, e crescimento de vagas que combinam conhecimento técnico com uso fluente de ferramentas de automação. Esses sinais já aparecem hoje em áreas como atendimento ao cliente, suporte administrativo e parte do trabalho de vendas, exatamente as categorias que a McKinsey aponta como mais expostas, o que dá tempo real para se preparar em vez de reagir depois que a vaga já não existe mais.</p>
  `,
};
