import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "melius-ia-agentes-criativos-anuncios-20-milhoes",
  title: "Melius capta US$ 20 milhões para agentes de IA que criam anúncios",
  summary:
    "Startup fundada por ex-engenheiros da Ramp abandonou o primeiro produto e virou uma 'agents lab' que gera campanhas, artes e vídeos para marcas.",
  author: "Bruno Danello",
  sourceName: "TechCrunch",
  sourceUrl:
    "https://techcrunch.com/2026/10/06/ex-ramp-engineers-raise-20m-for-platform-melius-after-scrapping-their-first-product/",
  date: "2026-10-06",
  publishedAt: "2026-10-07T04:35:00-03:00",
  imageQuery: "advertising creative studio laptop designer",
  topic: "negocios",
  content: `
    <p>A startup Melius anunciou nesta terça-feira (6) uma rodada Série A de US$ 20 milhões liderada pela CRV, somando US$ 25 milhões captados desde a fundação, incluindo uma rodada seed anterior de US$ 5 milhões liderada pela General Catalyst. Segundo reportagem do <a href="https://techcrunch.com/2026/10/06/ex-ramp-engineers-raise-20m-for-platform-melius-after-scrapping-their-first-product/" target="_blank" rel="noopener noreferrer nofollow">TechCrunch</a>, a empresa se descreve como uma "agents lab for creative work", uma plataforma de agentes de inteligência artificial que gera campanhas publicitárias, artes e vídeos para profissionais de marketing, agências e marcas a partir de comandos em linguagem natural.</p>

    <p>Os três fundadores, Joowon Kim, Young Kim e Arnav Ramu, são ex-engenheiros da fintech Ramp e passaram pela aceleradora Y Combinator antes de abrir a empresa. O produto atual nasceu de um pivô completo: nos primeiros seis meses, a equipe tentou construir uma ferramenta de otimização de gastos com anúncios baseada em IA, mas concluiu que a ideia "não tinha pernas" e descartou todo o código já escrito para recomeçar do zero focada em geração de material criativo. A aposta deu resultado rápido: a Melius saiu do modo discreto (stealth) em julho de 2026 e, em apenas dois meses, já alcançava mais de US$ 1 milhão em receita anualizada.</p>

    <h2>Um mercado que já tem concorrentes bilionários</h2>
    <p>A Melius entra em um espaço que já tem players consolidados e bem capitalizados. O Portal da AI já noticiou como a <a href="/noticias/higgsfield-video-ia-1-bilhao-receita-anualizada">Higgsfield, avaliada em US$ 5,4 bilhões, ultrapassou US$ 700 milhões em receita anualizada</a> gerando vídeos e campanhas com IA para o mesmo público de marcas e agências. Além da Higgsfield, a reportagem do TechCrunch cita Krea e Flora AI como concorrentes diretos nesse nicho de geração de conteúdo publicitário por agentes de IA. Mesmo cercado de rivais maiores e mais antigos, o cofundador Joowon Kim disse à publicação que vê a concorrência de forma positiva: "há muitos players, o que é bastante empolgante", numa leitura de que o mercado de criação de anúncios automatizada ainda está crescendo rápido o suficiente para caber vários vencedores.</p>
    <p>O histórico pessoal de Kim ajuda a explicar o foco do produto: ele se descreve como um entusiasta de redes sociais que sonhava em ser youtuber antes de se tornar engenheiro de software, e disse que concebeu a plataforma para "democratizar a produção criativa" para quem não tem equipe de design ou vídeo própria. Essa lógica de baixar a barreira de entrada para produção de conteúdo profissional é a mesma que já impulsiona ferramentas mais conhecidas no Brasil, como mostra o guia do Portal da AI sobre <a href="/artigos/canva-capcut-e-ia-artes-e-videos-sem-saber-design">Canva, CapCut e IA para criar artes e vídeos sem saber design</a>, só que a Melius mira direto o orçamento de marketing de empresas maiores, não o criador individual.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem presta serviço de marketing, atende clientes como freelancer ou tenta ganhar dinheiro criando conteúdo com apoio de inteligência artificial, o avanço de ferramentas como a Melius é um sinal direto de para onde o mercado está indo: cada vez mais, a etapa de produção de peça publicitária, seja imagem, vídeo ou campanha completa, está sendo automatizada por agentes que entendem um comando em texto e entregam o material pronto. Isso não elimina a necessidade de quem entende de estratégia e de cliente, mas muda o tipo de trabalho que vale cobrar: menos tempo gasto em execução manual de arte, mais tempo em direção criativa, aprovação e ajuste fino do que a IA produz. O Portal da AI já tratou desse tipo de mudança de função no guia sobre <a href="/artigos/como-ganhar-dinheiro-criando-videos-curtos-com-ia">como ganhar dinheiro criando vídeos curtos com IA</a>, que mostra como profissionais estão se reposicionando como curadores e diretores de conteúdo gerado por IA, em vez de produtores manuais de cada peça.</p>
    <p>Quem atende pequenos negócios locais também deve sentir esse movimento chegar via custo: plataformas como a Melius reduzem o preço de produzir campanha publicitária de qualidade, o que tende a pressionar para baixo o valor que agências e freelancers conseguem cobrar só pela execução. Como já descrevemos no artigo sobre <a href="/artigos/como-vender-pacotes-de-automacao-de-ia-para-negocios-locais">como vender pacotes de automação de IA para negócios locais</a>, a saída costuma ser empacotar o uso dessas ferramentas dentro de um serviço mais completo, cobrando pela estratégia e pelo resultado entregue ao cliente, não pela hora de produção da peça em si.</p>

    <h2>O padrão por trás da rodada: pivô rápido e tração antes de crescer</h2>
    <p>Chama atenção o fato de a Melius ter conseguido captar US$ 20 milhões em Série A apenas dois meses depois de lançar um produto completamente diferente do que vinha sendo construído nos seis meses anteriores. Esse padrão de "matar" uma ideia que não funcionou e redirecionar rapidamente para outra, usando a mesma equipe e parte da estrutura já levantada, tem se tornado comum entre startups de IA que competem por capital de risco: investidores parecem dar mais peso à velocidade de execução e à capacidade de identificar um produto com tração real do que à ideia original apresentada na rodada seed. Vale lembrar que o Portal da AI também acompanhou como a <a href="/noticias/anthropic-claude-startups-ano-gratis-creditos">Anthropic passou a oferecer um ano gratuito de Claude Team e créditos em token para startups</a>, um movimento que baixa a barreira de custo justamente para esse tipo de experimentação rápida com modelos de IA antes de encontrar o produto certo.</p>
    <p>Para quem acompanha o setor de ferramentas de criação com IA, como descrevemos no panorama sobre <a href="/artigos/ia-para-criadores-de-conteudo-videos-textos-e-artes">IA para criadores de conteúdo: vídeos, textos e artes</a>, o caso da Melius também serve de lembrete de que a oferta de produto nessa categoria muda rápido e que vale reavaliar periodicamente qual ferramenta entrega o melhor resultado para o fluxo de trabalho específico de cada profissional ou agência, em vez de se fixar numa única plataforma por hábito.</p>

    <h2>O que observar daqui para frente</h2>
    <p>Vale acompanhar se a Melius vai conseguir sustentar o ritmo de crescimento de receita depois da rodada, já que o salto de zero a US$ 1 milhão em receita anualizada em dois meses é um número inicial promissor, mas ainda pequeno diante de concorrentes como a Higgsfield, que já supera centenas de milhões em receita anualizada. Também é relevante observar se a empresa vai expandir para atender diretamente profissionais autônomos e pequenas agências brasileiras, hoje um público mais atendido por ferramentas como Canva e, cada vez mais, por geradores de vídeo como os comparados no guia sobre <a href="/artigos/runway-ou-pika-qual-ia-de-video-escolher">Runway ou Pika: qual IA de vídeo escolher</a>, ou se vai seguir focada em contratos maiores com marcas e agências de mídia nos Estados Unidos.</p>
    <p>Por fim, o episódio reforça que o mercado de geração de conteúdo publicitário por IA segue em disputa aberta, sem um vencedor claro ainda, o que é uma boa notícia para quem compra esse tipo de serviço: mais concorrência tende a significar preços mais competitivos e recursos evoluindo mais rápido, já que cada startup precisa se diferenciar para conquistar espaço num setor que já tem pelo menos três empresas avaliadas em centenas de milhões de dólares disputando o mesmo cliente final.</p>
  `,
};
