import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "mercado-paralelo-claude-china-revenda-tokens",
  title: "Mercado paralelo revende acesso ao Claude na China com até 90% de desconto",
  summary:
    "Revendedores chineses usam servidores no exterior e contas fraudulentas para driblar o bloqueio da Anthropic, vendendo acesso ao Claude por uma fração do preço oficial.",
  author: "Bruno Danello",
  sourceName: "IANS",
  sourceUrl:
    "https://ianslive.in/underground-market-for-anthropics-claude-surges-in-china-to-circumvent-blockage--20261005152930",
  date: "2026-10-05",
  content: `
    <p>Um mercado paralelo de revenda de acesso ao Claude continua crescendo na China, mesmo com a Anthropic proibindo oficialmente o uso de seus modelos no país. Segundo reportagem da <a href="https://ianslive.in/underground-market-for-anthropics-claude-surges-in-china-to-circumvent-blockage--20261005152930" rel="noopener noreferrer nofollow" target="_blank">IANS</a>, que cita levantamento do veículo sul-coreano The Chosun e da publicação The Information, pelo menos 6 de 30 empresas analisadas no distrito de Haidian, em Pequim, vivem da revenda de acesso à ferramenta, e o número de "estações de repasse" desse tipo é estimado em dezenas de milhares espalhadas pelo país.</p>

    <p>O esquema funciona com revendedores comprando em massa endereços de e-mail sobrando de antigos projetos de criptomoeda para cadastrar contas no Claude, depois revendidas a usuários chineses via WeChat e Alipay. Uma análise separada da pesquisadora Zilan Qian, do Oxford China Policy Lab, publicada pela newsletter <a href="https://the-decoder.com/how-chinas-gray-market-sells-claude-tokens-at-a-fraction-of-the-price/" rel="noopener noreferrer nofollow" target="_blank">The Decoder</a>, mostra que esses intermediários, chamados de "estações de transferência", cobram perto de 10% do preço oficial cobrado pela Anthropic.</p>

    <h2>Como o esquema contorna o bloqueio da Anthropic</h2>
    <p>A Anthropic não vende assinaturas do Claude para usuários na China continental, por razões regulatórias e de segurança nacional que já apareceram em outras notícias daqui, caso do <a href="/noticias/anthropic-glm-5-3-zhipu-riscos-ciberseguranca">alerta da própria empresa sobre riscos de modelos chineses como o GLM 5.3</a>. Para contornar essa barreira, os revendedores hospedam servidores-proxy fora do território chinês, que recebem a requisição do usuário local e a repassam à Anthropic como se tivesse origem numa localização autorizada, driblando tanto o bloqueio geográfico quanto a exigência de cartão de crédito internacional para pagamento.</p>
    <p>Entre as táticas mapeadas estão o uso de cartões de crédito virtuais vinculados a entidades de Hong Kong ou dos Estados Unidos e pagos em criptomoeda, fazendas de SMS que controlam números de telefone em jurisdições autorizadas para passar pela verificação por código da Anthropic, e a divisão de uma única assinatura Max de US$ 200 entre vários usuários simultâneos. Pesquisadores do CISPA Helmholtz Center analisaram 17 desses proxies e encontraram uma prática ainda mais grave: troca de modelo sem avisar o cliente. Em um dos casos, um endpoint vendido como acesso ao Claude na verdade respondia usando um modelo mais barato, com desempenho medido em benchmark médico de apenas 37%, contra 83,8% do modelo original contratado.</p>
    <p>A Anthropic já reagiu publicamente ao problema. Em março de 2026, a empresa acusou três companhias chinesas de criarem cerca de 24 mil contas fraudulentas, usadas em mais de 16 milhões de interações com o Claude para treinar modelos concorrentes com as respostas copiadas, episódio que reforça como o acesso irregular não serve só para economizar dinheiro, serve também para alimentar o treinamento de IA rival sem licenciamento.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem usa IA para trabalhar ou empreender no Brasil, o caso chinês é um alerta direto sobre um tipo de risco que também circula por aqui: serviços que prometem acesso "mais barato" a ferramentas de IA de ponta, driblando o plano oficial do provedor. O Portal da AI já mostrou como escolher ferramenta de IA com segurança importa tanto quanto escolher a ferramenta certa, e o esquema chinês é um exemplo extremo do que pode dar errado: o operador do proxy tem acesso completo ao que você digita e recebe, incluindo prompts com dados sensíveis de clientes, contratos ou código-fonte de empresa, e pode revender esse conteúdo como material de treinamento para outro modelo, sem o usuário nunca saber.</p>
    <p>O golpe de "troca de modelo" identificado pelo CISPA é ainda mais relevante para quem usa IA em decisão profissional: contratar acesso a um modelo de ponta e receber, sem aviso, respostas de um modelo mais fraco é um risco de qualidade silencioso, que só aparece quando o resultado do trabalho sai errado. Isso vale como lembrete de que vale a pena desconfiar de qualquer oferta de acesso "por fora" a ferramentas como Claude, ChatGPT ou Gemini, mesmo quando o preço parece vantajoso demais, situação que lembra outros casos recentes de <a href="/noticias/golpe-voz-ia-clonada-pix-compra-veiculo-familiar">fraude com IA mirando quem confia demais em canal digital barato ou informal</a>.</p>

    <h2>Um padrão que já apareceu em outras frentes da disputa China-EUA por IA</h2>
    <p>O mercado paralelo de tokens do Claude não é um caso isolado. Ele segue a mesma lógica vista em outra fronteira da disputa tecnológica entre China e Estados Unidos: a do contrabando de chips avançados de IA, tema que o Portal da AI já cobriu no caso de um <a href="/noticias/nvidia-executivo-contrabando-chips-china-eua">executivo investigado por contrabando de processadores Nvidia para a China</a>. Em ambos os casos, a demanda chinesa por tecnologia de IA de ponta é maior do que o acesso formal permitido pelas regras de exportação e pelas políticas das próprias empresas americanas, e isso cria um ecossistema de intermediários dispostos a assumir o risco legal em troca de margem.</p>
    <p>A estrutura descentralizada do esquema é o que torna o combate difícil. Segundo a reportagem, quando a Anthropic bloqueia um revendedor identificado em plataformas como o Taobao, outro substituto aparece em poucas horas, e os operadores mais sofisticados já criam empresas de fachada no Sudeste Asiático, no Oriente Médio e nos próprios Estados Unidos para firmar contratos empresariais legítimos com a Anthropic ou a AWS, dificultando ainda mais a identificação de uso indevido. A Anthropic afirma monitorar fuso horário e padrão de uso para detectar violações, mas a escala do problema, com dezenas de milhares de operações estimadas, sugere que a fiscalização está longe de acompanhar o crescimento do mercado paralelo.</p>

    <div class="callout-box">
      <span class="callout-label">O que fica diferente a partir de hoje</span>
      <p>O bloqueio de um provedor de IA a um país inteiro não impede o acesso, só empurra a demanda para um mercado informal sem nenhuma garantia de segurança ou qualidade. Para quem usa IA em qualquer lugar do mundo, o caso chinês é um lembrete concreto de que pagar menos por acesso "por fora" a uma ferramenta de IA pode significar entregar dados sensíveis a um intermediário desconhecido, ou receber um modelo mais fraco do que o contratado sem aviso nenhum.</p>
    </div>

    <h2>O que observar daqui para frente</h2>
    <p>Vale acompanhar três desdobramentos. O primeiro é se a Anthropic consegue de fato reduzir a escala do mercado paralelo com mais fiscalização, ou se a estrutura descentralizada dos revendedores continua tornando o combate ineficaz. O segundo é se outras provedoras de IA de ponta, caso de <a href="/artigos/chatgpt-claude-gemini-qual-ia-escolher">OpenAI e Google, que também restringem acesso formal à China</a>, enfrentam o mesmo tipo de mercado paralelo, o que sugeriria um problema estrutural do setor, não um caso isolado da Anthropic. O terceiro é se o episódio acelera a adoção de modelos chineses próprios, como o Qwen da Alibaba, reduzindo a demanda por acesso irregular a produtos ocidentais à medida que a oferta doméstica amadurece.</p>

    <p>Por ora, a lição prática para quem usa IA fora da China é simples: qualquer acesso barato demais a uma ferramenta de ponta merece desconfiança, e vale a pena revisar o checklist de segurança antes de contratar qualquer serviço de IA que prometa economia sem explicar como. O <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">guia do Portal da AI sobre como escolher ferramenta de IA com segurança</a> traz os pontos básicos que ajudam a identificar esse tipo de risco antes de comprometer dados sensíveis do seu trabalho ou negócio.</p>
  `,
};
