import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "meta-muse-gadgets-hardware-aberto-esp32",
  title: "Meta abre código do Muse Gadgets para criar hardware com IA",
  summary:
    "Meta lançou firmware open source para ESP32 e um SDK Linux que conectam o agente Muse a telas, botões e sensores, além de distribuir 5 mil unidades grátis de um dispositivo para casa.",
  author: "Bruno Danello",
  sourceName: "TechCrunch",
  sourceUrl: "https://techcrunch.com/2026/10/02/meta-wants-you-to-build-your-own-muse-gadget/",
  date: "2026-10-02",
  content: `
    <p>A Meta anunciou nesta sexta-feira (2) o Muse Gadgets, um projeto de código aberto que deixa qualquer desenvolvedor construir hardware próprio integrado ao Muse, o agente pessoal de IA da empresa. O anúncio foi feito por Nat Friedman, chefe de produto do Meta Superintelligence Labs, em uma publicação no X na qual descreveu o lançamento como "um firmware open source para ESP32 e um SDK Linux para que você possa fazer dispositivos de hardware que funcionem com o Muse". Segundo reportagem do <a href="https://techcrunch.com/2026/10/02/meta-wants-you-to-build-your-own-muse-gadget/" target="_blank" rel="noopener noreferrer nofollow">TechCrunch</a>, a iniciativa marca a primeira vez que a Meta abre formalmente a porta de entrada de hardware do Muse para a comunidade de desenvolvedores e entusiastas.</p>

    <p>O pacote liberado no GitHub, no repositório <code>facebookincubator/muse-gadget-sdk</code>, sob licença Apache 2.0, inclui dois caminhos de desenvolvimento: um SDK para placas ESP32, os microcontroladores baratos e populares entre makers, e um SDK Linux voltado a Raspberry Pi e computadores de placa única parecidos. Com qualquer um dos dois, é possível plugar o Muse a telas, botões, sensores e atuadores, ou seja, qualquer peça eletrônica que esteja disponível na bancada de quem está montando o projeto. A Meta também publicou sete exemplos de projetos prontos para servir de ponto de partida, incluindo o uso do Seeed reTerminal E1002 para exibir resumos de agenda em uma tela de tinta eletrônica e o M5Stack StickS3 como dispositivo portátil com tela própria.</p>

    <h2>O que é o Muse e por que a Meta está abrindo esse acesso agora</h2>
    <p>O Muse é o agente pessoal de IA da Meta, acessado hoje pelo aplicativo próprio ou pelo WhatsApp, que já cuida de tarefas como responder e-mail, fazer reservas e organizar compromissos. Nos últimos meses a empresa ampliou o alcance do produto para outras frentes: lançou o Muse for Small Business, com integrações a Shopify, Dropbox e Slack voltadas a pequenos negócios, e criou a Meta Enterprise Platform, uma unidade de negócios dedicada a vender o agente para clientes corporativos. O Muse Gadgets é o próximo passo dessa expansão, e talvez o mais ambicioso: em vez de levar o Muse para dentro de outros softwares, a aposta agora é levá-lo para fora da tela, para objetos físicos que qualquer pessoa pode montar em casa.</p>
    <p>Essa mesma publicação trouxe outro anúncio complementar, o Muse Home Link, um dispositivo conectado por USB-C que liga o Muse à rede doméstica e permite que o agente controle aparelhos compatíveis, como TVs e caixas de som inteligentes, além de qualquer equipamento que exponha uma interface web local. A Meta está distribuindo 5 mil unidades de graça para assinantes ativos do Muse nos Estados Unidos, limitado a um dispositivo por pessoa, com envios começando em outubro por ordem de chegada. É um movimento clássico de quem quer construir um ecossistema de hardware rápido: dar a peça de entrada de graça para baratear o primeiro contato do usuário com a ideia.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você trabalha com tecnologia, cria produtos ou presta serviço de automação no Brasil, o Muse Gadgets é um sinal concreto de para onde os grandes laboratórios de IA estão olhando depois de dominar o chat e o navegador: hardware físico barato, acessível para quem não tem orçamento de grande empresa. Um ESP32 custa poucos dólares e já é usado há anos por makers brasileiros em projetos de automação residencial; agora esse mesmo microcontrolador pode virar porta de entrada para um agente de IA completo, sem precisar escrever a parte difícil de integração do zero. Para quem já entende o básico de ferramentas de IA e quer dar o próximo passo, pode ser uma oportunidade real de criar um produto físico de nicho, como um painel de recados inteligente para escritório ou um assistente de voz customizado para um comércio local.</p>
    <p>Vale lembrar que isso também é parte de uma corrida mais ampla entre as grandes empresas de IA para colocar agentes em todo lugar possível, não só no hardware. A Meta está fazendo isso com objetos físicos, enquanto a <a href="/noticias/openai-lanca-dots-agentes-sempre-ativos-gpt-6-1-sol">OpenAI apostou em agentes sempre ativos chamados Dots</a> dentro do próprio navegador e aplicativo, e startups como a <a href="/noticias/photon-agentes-ia-whatsapp-imessage">Photon levantaram capital para colocar agentes dentro de WhatsApp e iMessage</a>. O padrão se repete: quem construir a integração mais simples e mais barata para o desenvolvedor comum tende a conquistar a base de usuários mais ampla, e não necessariamente quem tem o modelo de linguagem mais avançado. Para quem está decidindo qual assistente de IA faz mais sentido para o próprio uso, vale conferir nosso <a href="/artigos/chatgpt-claude-gemini-qual-ia-escolher">comparativo entre ChatGPT, Claude e Gemini</a>.</p>

    <div class="callout-box callout-tip">
      <span class="callout-label">O que você precisa para começar</span>
      <p>Segundo a documentação liberada pela Meta, o ponto de partida é pegar um token de API gratuito no site <code>gadgets.muse.ai</code> e usar uma placa ESP32 comum, encontrada facilmente em lojas de eletrônica no Brasil por valores baixos, ou um Raspberry Pi já disponível. A partir daí, o próprio repositório no GitHub traz os exemplos de projeto e a documentação de como conectar sensores, telas e botões ao agente.</p>
    </div>

    <h2>O que observar nos próximos meses</h2>
    <p>Três pontos merecem atenção de quem acompanha o setor. O primeiro é se a comunidade de makers vai de fato adotar o projeto, algo que depende de documentação clara e suporte ativo da Meta no canal de Discord que a empresa abriu para a iniciativa, já que projetos open source de grandes empresas às vezes perdem força depois do anúncio inicial. O segundo é se concorrentes como Google e Amazon, que já têm linhas de hardware doméstico consolidadas com Google Home e Alexa, vão responder com movimentos parecidos de abertura para desenvolvedores externos, algo que ainda não aconteceu nessa escala. O terceiro é se a Meta vai expandir o programa de unidades gratuitas do Muse Home Link para fora dos Estados Unidos, o que determinaria se o Brasil vai ter acesso fácil a essa porta de entrada ou vai precisar importar o dispositivo.</p>
    <p>Para o leitor que já usa automações de IA no trabalho ou no próprio negócio, o conselho prático é acompanhar de longe por enquanto: é um projeto recém-lançado, sem histórico de estabilidade, e qualquer produto comercial construído sobre ele hoje corre o risco de precisar de ajustes quando a Meta atualizar o SDK. Mas para quem gosta de testar tecnologia nova e já tem familiaridade com eletrônica básica, é um dos poucos projetos de hardware com IA que chegam gratuitos, abertos e prontos para rodar fora dos laboratórios das grandes empresas.</p>
  `,
};
