import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "newsom-veta-lei-oculos-inteligentes-gravacao-espiao",
  title: "Newsom veta lei contra uso de óculos com IA para gravar às escondidas",
  summary:
    "O governador da Califórnia considerou o projeto SB 1130 amplo demais, dias antes do lançamento de novos óculos da Samsung e em meio ao crescimento das vendas dos óculos da Meta.",
  author: "Bruno Danello",
  sourceName: "TechCrunch",
  sourceUrl: "https://techcrunch.com/2026/10/01/california-governor-vetoes-bill-banning-use-of-pervert-glasses-to-secretly-record-people/",
  date: "2026-10-01",
  content: `
    <p>O governador da Califórnia, Gavin Newsom, vetou nesta quarta-feira (30) o projeto de lei SB 1130, que criaria punição criminal para quem usasse óculos inteligentes equipados com câmera para gravar som ou imagem de outra pessoa sem consentimento, em locais onde ela tivesse expectativa razoável de privacidade, como vestiários e consultórios médicos. O texto também obrigaria fabricantes a incluir um indicador visível de gravação nesse tipo de dispositivo e proibiria a venda de tecnologia capaz de esconder essa luz. Segundo reportagem do <a href="https://techcrunch.com/2026/10/01/california-governor-vetoes-bill-banning-use-of-pervert-glasses-to-secretly-record-people/" rel="noopener noreferrer nofollow">TechCrunch</a>, o projeto ficou conhecido informalmente como lei dos "óculos de pervertido", por ter sido pensado especificamente contra o uso de óculos com IA para gravar pessoas em situações íntimas sem que elas soubessem.</p>
    <p>Na justificativa do veto, Newsom disse que a definição de "dispositivo de gravação vestível" usada no projeto era abrangente demais, já que incluía qualquer equipamento "projetado para ser usado no corpo, em vez de carregado na mão", com capacidade de gravar ou transmitir som ou vídeo. Na prática, isso incluiria smartwatches e outros dispositivos comuns, amplamente usados em espaços públicos. O governador afirmou que essa definição "poderia incluir certos smartwatches ou outros dispositivos vestíveis amplamente usados em espaços públicos e capazes de gravar, o que poderia levar a confusão significativa e consequências não pretendidas". Ele também apontou que a Califórnia já proíbe o uso de qualquer dispositivo eletrônico para gravar outras pessoas em locais com expectativa razoável de privacidade, tornando parte da nova lei redundante.</p>

    <h2>O timing do veto e o mercado de óculos com IA</h2>
    <p>O momento do veto não passou despercebido. Segundo o site <a href="https://hoodline.com/2026/10/newsom-vetoes-smart-glasses-spy-bill-as-meta-device-sales-top-7-million/" rel="noopener noreferrer nofollow">Hoodline</a>, as vendas de óculos com IA da Meta, feitos em parceria com a Ray-Ban, já superaram 7 milhões de unidades, e a decisão chega poucas semanas antes do lançamento dos óculos inteligentes da Samsung no mercado americano. A categoria de óculos equipados com câmera e assistente de IA deixou de ser nicho: Meta, Samsung, Google e startups menores disputam esse mercado, apostando que o óculos será o próximo grande dispositivo de computação pessoal depois do smartphone, como já discutimos em <a href="/artigos/ia-multimodal-o-que-muda-quando-maquina-ve-ouve-fala">IA multimodal e o que muda quando a máquina vê, ouve e fala</a>.</p>
    <p>O problema de privacidade que o SB 1130 tentava resolver não é exclusivo da Califórnia nem novo: desde que a Meta lançou seus primeiros óculos com câmera discreta, em parceria com a Ray-Ban, especialistas em privacidade alertam que a luz indicadora de gravação é pequena, fácil de obscurecer e insuficiente para avisar quem está sendo filmado. Outros estados americanos e países já discutem regras parecidas, mas a Califórnia, sede da maioria das grandes empresas de tecnologia, costuma funcionar como referência para o que vem depois em outras jurisdições.</p>

    <h2>Por que isso importa para você</h2>
    <p>O Brasil ainda não tem uma lei específica sobre óculos ou outros dispositivos vestíveis com câmera embutida, mas o caso californiano serve de alerta sobre um problema que já existe por aqui: qualquer pessoa que usa um óculos com IA, como os da linha Ray-Ban Meta vendidos oficialmente no país, pode gravar quem está à sua frente sem que a outra pessoa perceba, já que o indicador luminoso é discreto e muitas vezes passa despercebido em ambientes claros ou movimentados. Quem compra esse tipo de dispositivo para uso profissional, como registrar reuniões ou atendimentos, precisa redobrar o cuidado de avisar explicitamente quem está sendo filmado, até porque a Lei Geral de Proteção de Dados (LGPD) já trata a gravação de imagem e voz de terceiros sem consentimento como tratamento de dados pessoais sujeito a regras próprias, independente de existir uma lei específica sobre óculos inteligentes.</p>
    <p>Para quem trabalha vendendo ou recomendando ferramentas de IA para pequenas empresas, o episódio também é um recado sobre como a regulação de hardware com IA embutida tende a andar atrás da tecnologia, não na frente dela: a Meta já vendeu milhões de unidades de óculos com câmera antes de qualquer estado americano aprovar uma lei específica sobre o indicador de gravação, e mesmo agora, quando uma lei chegou a ser aprovada pelo Legislativo californiano, ela foi vetada por imprecisão técnica. Isso significa que, na prática, a responsabilidade de usar esse tipo de dispositivo de forma ética recai sobre quem compra e usa, não sobre uma regra pronta que impeça o abuso.</p>

    <h2>O que observar daqui para frente</h2>
    <p>Vale acompanhar se a Assembleia Legislativa da Califórnia vai reapresentar uma versão mais estreita do SB 1130, corrigindo a definição de "dispositivo vestível" apontada por Newsom como problema central, algo que o próprio texto do veto sugere ser possível. Também é um bom momento para observar se a Meta, a Samsung ou a Google vão antecipar críticas regulatórias com mudanças voluntárias no design dos próprios óculos, como indicadores de gravação mais visíveis ou sons de alerta quando a câmera é ativada, movimento que já aconteceu em outras categorias de produto sob pressão pública antes de uma lei formal existir.</p>
    <p>No Brasil, o debate sobre regras específicas para dispositivos de IA vestíveis ainda deve demorar a aparecer no Congresso, já que a prioridade regulatória atual está concentrada no projeto de lei geral de IA, como mostramos em <a href="/artigos/lei-de-ia-no-brasil-o-que-muda-para-quem-usa">lei de IA no Brasil, o que muda para quem usa</a>. Enquanto isso não avança, quem usa ou vende esse tipo de óculos no país segue dependendo das regras gerais de privacidade já existentes, como a própria LGPD e o direito à imagem previsto no Código Civil, para lidar com casos de gravação não autorizada.</p>
  `,
};
