import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "nyc-council-intima-spacexai-musk-audiencia-ia",
  title: "Câmara de Nova York intima SpaceXAI de Musk antes de audiência sobre IA",
  summary:
    "OpenAI, Anthropic, Google e Meta aceitaram testemunhar sob juramento sobre riscos da IA, mas a SpaceXAI de Musk não respondeu e foi intimada pela Câmara de NY",
  author: "Bruno Danello",
  sourceName: "New York City Council",
  sourceUrl: "https://council.nyc.gov/press/2026/09/28/3266/",
  date: "2026-10-05",
  content: `
    <p>A presidente da Câmara de Vereadores de Nova York, Julie Menin, intimou a SpaceXAI, empresa de Elon Musk que reúne X e o chatbot Grok, para comparecer à audiência sobre riscos da inteligência artificial marcada para esta segunda-feira, 5 de outubro. Segundo <a href="https://council.nyc.gov/press/2026/09/28/3266/" rel="noopener noreferrer nofollow" target="_blank">comunicado oficial da Câmara</a>, a intimação foi necessária porque a SpaceXAI, diferente de OpenAI, Anthropic, Google e Meta, não respondeu aos pedidos de participação voluntária até o prazo de 25 de setembro.</p>

    <p>As outras quatro empresas só confirmaram presença depois que Menin deixou claro que poderia recorrer ao poder de intimação. OpenAI e Google aceitaram no domingo antes do prazo, a Anthropic confirmou já no fim da noite de domingo, e a Meta foi a única a aceitar de imediato. Caso a SpaceXAI não cumpra a intimação, a Câmara informou que pode buscar execução judicial na Suprema Corte do estado de Nova York.</p>

    <h2>Uma sessão rara com os 51 vereadores</h2>
    <p>A audiência de hoje usa o formato "Committee of the Whole", que reúne de uma só vez todos os 51 vereadores da cidade e não era convocado desde 2022. A convocação, anunciada em 25 de setembro, já havia sido coberta pelo <a href="/noticias/nyc-council-projetos-lei-regulacao-ia-kill-switch-denuncia">Portal da AI quando a Câmara anunciou o pacote de projetos de lei</a> que inclui validação externa obrigatória de sistemas de IA, "kill switch" de emergência e recompensas para denunciantes. Na época, Menin havia enviado cartas aos CEOs das cinco empresas e apenas reservado o direito de usar poder de intimação; agora esse poder foi exercido de fato contra a SpaceXAI.</p>
    <p>Segundo a Câmara, a investigação por trás da audiência busca apurar se os riscos de segurança da IA "justificam ação legislativa imediata para proteger os nova-iorquinos", olhando para ameaças à segurança pública, cibersegurança, estabilidade econômica, privacidade e interesses de consumidores e empresas. Entre os convidados a testemunhar está o ex-pesquisador da Anthropic Jacob Coxon, que deixou a empresa alertando sobre riscos de segurança, episódio semelhante ao de outros pesquisadores que saíram recentemente de laboratórios de IA, como mostrou a <a href="/noticias/david-robinson-openai-demissao-cultura-seguranca">saída do responsável por relatórios de segurança da OpenAI</a>.</p>

    <h2>Por que a SpaceXAI está sob mais pressão</h2>
    <p>A SpaceXAI nasceu em fevereiro de 2026 da fusão entre a SpaceX e a xAI de Musk, reunindo a rede social X e o chatbot Grok numa só empresa, que abriu capital em junho com valor de mercado em torno de US$ 2 trilhões e no mês passado comprou a startup de programação com IA Cursor por US$ 60 bilhões. A empresa enfrenta hoje múltiplos processos depois que o Grok gerou imagens pornográficas não consensuais com deepfake, incluindo uma ação de proteção ao consumidor movida por Baltimore e ações coletivas de adolescentes que alegam ter sido alvo de imagens sexualizadas geradas pelo chatbot.</p>
    <p>Esse histórico ajuda a explicar por que a Câmara tratou a falta de resposta da SpaceXAI de forma diferente das demais empresas. Um caso parecido já havia chegado à Justiça americana: no mês passado, um <a href="/noticias/minnesota-nudify-xai-liminar-tribunal-apelacao">tribunal de apelações suspendeu uma lei de Minnesota contra aplicativos de "nudificação" por IA</a> depois que a xAI (hoje parte da SpaceXAI) questionou a norma na Justiça, alegando restrição à liberdade de expressão.</p>

    <h2>Por que isso importa para quem trabalha e empreende com IA no Brasil</h2>
    <p>Nenhuma lei aprovada em Nova York vale fora dos Estados Unidos, mas o episódio importa para quem usa ferramentas de IA no Brasil por dois motivos práticos. Primeiro, porque mostra que reguladores locais, não só governos federais, já têm poder de forçar big techs a prestar contas em público, um movimento que tende a se espalhar e influenciar como plataformas como ChatGPT, Gemini, Claude e Grok ajustam seus próprios termos de uso e políticas de segurança globalmente, inclusive para usuários brasileiros. Segundo, porque o foco da audiência em "kill switch", notificação de incidentes e validação externa de sistemas de IA é o tipo de exigência que, se adotada por outras cidades ou países, pode se tornar padrão de mercado mesmo onde não existe lei equivalente, da mesma forma que o <a href="/noticias/processo-antitruste-anthropic-openai-google-xai-desaceleracao">processo antitruste contra Anthropic, OpenAI, Google e SpaceXAI por suposta desaceleração coordenada</a> já expôs que as próprias empresas discutem internamente até onde vale a pena acelerar lançamentos.</p>
    <p>Para quem usa Grok, X ou qualquer produto ligado à SpaceXAI em operações no Brasil, vale acompanhar o desfecho da audiência e das ações judiciais citadas: processos por deepfake e resistência a fiscalização pública são sinais de risco reputacional e jurídico que podem se traduzir em mudanças repentinas de política de uso, bloqueios de recursos ou até suspensão de funcionalidades, como já ocorreu antes em outras disputas envolvendo xAI e seus produtos.</p>

    <h2>O que observar depois da audiência</h2>
    <p>Três desdobramentos valem monitoramento nas próximas semanas: se a SpaceXAI de fato comparece ou se a Câmara precisa acionar a Justiça para fazer valer a intimação; quais compromissos específicos OpenAI, Anthropic, Google e Meta assumem em relação às propostas de "kill switch" e notificação de incidentes em 24 horas; e se o modelo de audiência pública sob juramento adotado em Nova York inspira iniciativas parecidas em outras cidades americanas ou mesmo em discussões legislativas no Brasil, onde o debate sobre regulação de IA segue concentrado no Congresso e ainda sem desfecho sobre o marco legal da IA.</p>

    <div class="callout-box">
      <span class="callout-label">O que fica diferente a partir de hoje</span>
      <p>Independente do resultado da sessão, o precedente já está criado: uma câmara municipal nos Estados Unidos conseguiu, com uma simples intimação, fazer com que quatro das maiores empresas de IA do mundo concordassem em depor sob juramento sobre riscos de seus próprios produtos, algo que o Congresso americano, mais fragmentado e sujeito a lobby direto das big techs, não conseguiu emplacar até agora. Isso muda o cálculo de risco de qualquer empresa de IA que opere nos Estados Unidos: ignorar um pedido formal de uma autoridade local pode custar mais caro, em exposição pública e risco jurídico, do que simplesmente comparecer e responder perguntas.</p>
    </div>

    <p>Para quem acompanha o setor a partir do Brasil, o episódio também serve como termômetro de como o mercado tende a reagir à pressão regulatória crescente sobre agentes autônomos e chatbots cada vez mais integrados ao dia a dia de empresas e consumidores. Enquanto ferramentas como ChatGPT, Gemini e Claude se tornam parte da rotina de quem trabalha com marketing, atendimento ou programação, episódios como esse mostram que a confiança nessas ferramentas também depende de como as empresas por trás delas respondem, ou deixam de responder, quando questionadas publicamente sobre segurança. Um fornecedor de IA disposto a prestar contas em público tende a ser uma aposta mais segura no longo prazo do que um que só age sob ameaça judicial, um critério que vale tanto para quem escolhe ferramenta pessoal quanto para empresas que integram IA em seus produtos.</p>
  `,
};
