import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "perplexity-computer-automations-slack-gmail",
  title: "Perplexity lança Automations, rotinas que rodam sozinhas no Computer",
  summary:
    "O recurso deixa o agente Computer, da Perplexity, disparar tarefas por horário ou por evento em Slack, Gmail, Outlook, Linear e GitHub, com memória entre execuções.",
  author: "Bruno Danello",
  sourceName: "Alpha Signal",
  sourceUrl: "https://alphasignal.ai/news/perplexity-s-computer-agent-now-automates-recurring-work-across-slack-gmail-and",
  date: "2026-09-29",
  content: `
    <p>A Perplexity lançou o Automations, novo recurso do Computer, seu agente de IA capaz de pesquisar, escrever código e executar tarefas completas. Segundo informou a própria empresa, de acordo com reportagem do site especializado <a href="https://alphasignal.ai/news/perplexity-s-computer-agent-now-automates-recurring-work-across-slack-gmail-and" rel="noopener noreferrer nofollow">Alpha Signal</a>, o Automations permite que o agente dispare ações sozinho, por horário programado ou em resposta a eventos em aplicativos conectados, como uma mensagem nova no Slack ou um e-mail que chega no Gmail.</p>
    <p>A diferença em relação ao que o Computer já fazia é a persistência: antes, cada execução do agente era isolada, como uma conversa que começa do zero. Com o Automations, cada rodada carrega a memória das execuções anteriores, então o agente consegue, por exemplo, acompanhar um projeto ao longo de semanas sem perder o contexto do que já foi feito. O recurso substitui a antiga interface de "Scheduled Tasks" (tarefas agendadas) da Perplexity, e as automações antigas migram automaticamente para o novo painel.</p>

    <h2>Como funciona e com quais apps se conecta</h2>
    <p>O Automations se conecta a Slack, Gmail, Outlook, Linear e GitHub, usando filtros condicionais para decidir quando uma automação deve ou não disparar. A Perplexity também destaca uma função de monitoramento passivo: o agente pode ficar de olho em prazos perdidos ou respostas em atraso e avisar o usuário, sem gastar créditos enquanto só está observando (o consumo só acontece quando a automação de fato executa uma ação). Para tarefas sensíveis, como enviar um e-mail em nome do usuário, o sistema inclui etapas de aprovação humana antes de concluir a ação.</p>
    <p>O lançamento faz parte da estratégia mais ampla da Perplexity de transformar seu buscador de IA em uma plataforma completa de produtividade, batizada de Computer, que já conta com versão para empresas, cliente para Windows e até uma versão local para hardware da Nvidia. A empresa também expandiu recentemente seu navegador <a href="/noticias/perplexity-comet-navegador-ia-disponivel-todos-usuarios-ios">Comet para todos os usuários de iOS</a>, e já testou o uso de IA generativa em contextos sensíveis no Brasil, como mostramos na cobertura sobre o <a href="/noticias/its-rio-boca-de-ia-perplexity-recomenda-candidatos-tse">uso do Perplexity para recomendar candidatos nas eleições</a>, caso que gerou questionamento do TSE.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você já usa Zapier, Make ou algum fluxo de automação para seu negócio, vale observar o Automations de perto: diferente das ferramentas tradicionais de automação, que conectam gatilhos a ações pré-definidas, o Computer da Perplexity usa um agente de IA no meio do processo, capaz de interpretar o conteúdo de um e-mail ou mensagem e decidir a ação mais adequada, não só executar um script fixo. Isso aproxima a Perplexity de concorrentes como os agentes sempre ativos que a <a href="/noticias/openai-lanca-dots-agentes-sempre-ativos-gpt-6-1-sol">OpenAI lançou com os Dots</a>, no DevDay, mostrando que "agente que trabalha sozinho em segundo plano" virou a aposta comum dos grandes players de IA para 2026.</p>
    <p>Para quem vende serviço de automação para pequenos negócios no Brasil, como já discutimos no comparativo entre <a href="/artigos/make-ou-zapier-qual-automacao-com-ia-vale-mais-a-pena">Make e Zapier</a>, essa onda de "automação com agente" é tanto ameaça quanto oportunidade: ameaça porque ferramentas como o Computer podem, no futuro, substituir parte do trabalho de configurar fluxos simples; oportunidade porque clientes ainda vão precisar de alguém que entenda o negócio para desenhar quais automações fazem sentido, conectar as contas certas e revisar se o agente está tomando as decisões corretas, principalmente em etapas que envolvem aprovação humana.</p>

    <h2>O que acompanhar na prática</h2>
    <p>Vale ficar de olho em como a Perplexity vai lidar com erros do agente em automações recorrentes: um fluxo de automação tradicional falha de forma previsível (o gatilho não dispara, a ação dá erro), mas um agente de IA pode interpretar errado o conteúdo de um e-mail ou tomar uma decisão inesperada, o que exige camadas extras de confiança antes de liberar o recurso para tarefas críticas de uma empresa, como faturamento ou atendimento ao cliente. A exigência de aprovação humana em ações sensíveis é um primeiro sinal de que a própria Perplexity reconhece esse risco.</p>
    <p>Outro ponto a observar é o modelo de cobrança: como o consumo de crédito só acontece na execução, não no monitoramento, o custo de manter várias automações ativas ao mesmo tempo tende a ficar mais previsível do que em ferramentas que cobram por tempo de monitoramento constante. Para quem pretende adotar o Automations em fluxos de trabalho no Brasil, o recomendável é começar por tarefas de baixo risco, como resumir e-mails ou organizar tarefas no Linear, antes de confiar o recurso a processos que envolvem dinheiro ou comunicação direta com clientes.</p>

    <h2>Agente com memória é diferente de automação por gatilho</h2>
    <p>A diferença técnica entre o Automations e uma ferramenta tradicional de automação, como Zapier ou Make, está na forma como cada uma lida com exceções. Numa automação clássica, o fluxo segue sempre o mesmo caminho predefinido: se o e-mail chegou, execute a ação X. Já o agente do Computer consegue olhar o conteúdo do e-mail, interpretar o contexto e decidir se aquela mensagem realmente exige ação, ou se deve só ser registrada e ignorada por enquanto. Essa flexibilidade reduz o trabalho de configurar dezenas de regras condicionais manualmente, mas também introduz uma camada de imprevisibilidade que ferramentas de automação tradicionais não têm, já que o comportamento do agente depende do modelo de linguagem por trás dele, não de um script fixo escrito por um humano.</p>
    <div class="callout-box">
      <span class="callout-label">Para quem usa IA no trabalho</span>
      <p>Se a sua empresa já usa Slack, Gmail, Outlook, Linear ou GitHub no dia a dia, o Automations pode substituir parte do trabalho manual de acompanhar threads, conferir prazos e registrar pendências, mas vale testar primeiro em um canal ou projeto de baixo risco, revisando as primeiras execuções de perto antes de confiar o recurso a um fluxo crítico do negócio.</p>
    </div>
    <p>Essa tensão entre flexibilidade e previsibilidade é um dos temas centrais de quem avalia <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">como escolher ferramenta de IA com segurança</a>, especialmente quando o agente tem acesso a contas corporativas sensíveis, como caixa de e-mail e repositórios de código. Para profissionais e pequenas empresas brasileiras que vendem serviço de automação, o Automations da Perplexity reforça a tendência de que o diferencial competitivo deixa de ser "montar o fluxo técnico" e passa a ser "garantir que o agente toma as decisões certas", um trabalho que exige mais acompanhamento humano contínuo do que a automação tradicional baseada em regras fixas.</p>
  `,
};
