import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "restate-capta-20-milhoes-infraestrutura-agentes-ia",
  title: "Restate capta US$ 20 milhões para dar confiabilidade a agentes de IA",
  summary:
    "Startup alemã fundada por criadores do Apache Flink levanta Série A para evitar que agentes de IA dupliquem pagamentos e percam estado ao falhar.",
  author: "Bruno Danello",
  sourceName: "Unite.AI",
  sourceUrl: "https://www.unite.ai/restate-raises-20m-series-a-to-build-durable-infrastructure-for-ai-agents/",
  date: "2026-09-30",
  content: `
    <p>A Restate, startup com sede em Berlim e São Francisco, anunciou nesta terça-feira uma rodada Série A de US$ 20 milhões para expandir sua infraestrutura de "execução durável" voltada a agentes de inteligência artificial. A rodada foi liderada pela gestora Singular, com participação da Redpoint Ventures e da Capital One Ventures, elevando o total captado pela empresa a US$ 27 milhões, segundo apuração do <a href="https://www.unite.ai/restate-raises-20m-series-a-to-build-durable-infrastructure-for-ai-agents/" target="_blank" rel="noopener noreferrer nofollow">Unite.AI</a>.</p>

    <p>A empresa foi fundada por parte da equipe que criou o Apache Flink, o framework de código aberto que se tornou referência em processamento de dados em tempo real na última década. Com a Restate, o grupo decidiu atacar um problema mais recente e específico: o que acontece quando um agente de IA que está no meio de uma tarefa longa (como processar um pagamento, agendar uma viagem ou revisar um contrato em várias etapas) simplesmente trava ou perde a conexão antes de terminar.</p>

    <h2>O problema que a Restate resolve</h2>
    <p>Diferente de um chatbot que responde uma pergunta e encerra, um agente de IA moderno costuma executar dezenas ou centenas de passos encadeados: ele chama uma API, espera uma aprovação humana, consulta um banco de dados, chama outra IA para revisar o resultado, e só então age. Se qualquer um desses passos falhar no meio do caminho (uma queda de rede, um servidor reiniciando, um limite de uso excedido), o risco é o agente repetir uma cobrança já feita, duplicar uma chamada de API que tem custo, perder uma aprovação que já havia sido dada por um humano ou simplesmente desperdiçar todo o processamento de modelo já pago até ali.</p>
    <p>A plataforma da Restate ataca esse problema registrando cada operação concluída e o estado do agente em um log distribuído próprio, combinado com um orquestrador orientado a eventos. Na prática, isso permite que a aplicação retome exatamente do ponto correto depois de uma falha, sem repetir etapas já concluídas e sem precisar de um banco de dados externo adicional, o que mantém o runtime leve e fácil de operar segundo a empresa.</p>

    <h2>De ferramenta de nicho a infraestrutura usada por gigantes</h2>
    <p>A Restate afirma que centenas de empresas já usam sua tecnologia, incluindo companhias da lista Fortune 500. O exemplo mais citado é o Replit Agent, ferramenta de programação assistida por IA que usa a Restate para orquestrar de forma confiável fluxos de trabalho de codificação que chegam a milhares de etapas encadeadas sem perder o controle do processo. Outros clientes mencionados publicamente incluem a DOSS e a BILT Rewards. Com o novo aporte, a empresa planeja expandir sua presença nos Estados Unidos, incluindo a abertura de um polo comercial em São Francisco, além de continuar o desenvolvimento de uma opção "Bring Your Own Cloud" voltada a clientes corporativos que precisam manter os dados dentro da própria infraestrutura de nuvem.</p>
    <p>O momento da captação não é coincidência. Ao longo de 2026, uma sequência de incidentes públicos envolvendo agentes de IA que agiram fora do esperado (o <a href="/noticias/agentes-openai-15-incidentes-seguranca-investigacao">Portal da AI já cobriu pelo menos 15 casos documentados só envolvendo a OpenAI</a>, incluindo vazamento de dados e acessos não autorizados) colocou a confiabilidade e a previsibilidade de agentes autônomos no centro das atenções de quem decide investir em IA dentro de empresas. A própria Microsoft relatou como um grupo de ransomware usou um agente de IA para apagar recursos inteiros de uma conta na nuvem Azure em minutos, episódio detalhado em <a href="/noticias/jadepuffer-ransomware-ia-azure-microsoft">outra reportagem do Portal da AI</a>. Investidores e empresas de infraestrutura como a Restate apostam que parte da solução para esse tipo de risco passa menos por "IA mais inteligente" e mais por engenharia de software tradicional e rigorosa por trás da cena.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você usa ou está pensando em automatizar processos do seu negócio com agentes de IA, seja via <a href="/artigos/make-ou-zapier-qual-automacao-com-ia-vale-mais-a-pena">Zapier, Make ou uma automação mais sofisticada</a>, essa notícia aponta para uma mudança de maturidade no mercado: a conversa deixou de ser só "o agente consegue fazer a tarefa" e passou a incluir "o que acontece quando algo dá errado no meio do caminho". Isso é bom para quem usa essas ferramentas no dia a dia, porque significa que a infraestrutura por trás de produtos de agente está ficando mais robusta, reduzindo o risco de uma automação duplicar um pagamento ou travar com uma tarefa pela metade sem avisar ninguém.</p>
    <p>Na prática, ao avaliar qualquer ferramenta que prometa automação "autônoma" de tarefas críticas (cobranças, agendamentos, atualizações de estoque, respostas a clientes), vale perguntar ao fornecedor como ele trata falhas no meio de um processo: existe um registro do que já foi feito? O sistema evita repetir uma ação já concluída? Existe algum ponto de revisão humana antes de ações irreversíveis, como um pagamento ou o envio de uma mensagem em massa? Nosso <a href="/artigos/como-escolher-ferramenta-de-ia-com-seguranca-checklist">checklist de como escolher ferramenta de IA com segurança</a> trata exatamente desse tipo de pergunta, e é ainda mais relevante à medida que mais negócios brasileiros adotam agentes de IA para tarefas do dia a dia.</p>

    <h2>O que esperar daqui para frente</h2>
    <p>A tendência é que mais empresas de infraestrutura "de bastidor" para agentes de IA, como a Restate, ganhem investimento ao longo dos próximos meses, à medida que o mercado amadurece da fase de "demonstração impressionante" para a fase de "rodando em produção com dinheiro real envolvido". Esse tipo de camada invisível tende a não aparecer em manchetes vistosas, mas é o que vai determinar se os agentes de IA cada vez mais presentes em <a href="/artigos/agentes-de-ia-o-futuro-do-trabalho-autonomo-explicado">processos de trabalho autônomo</a> conseguem operar com confiabilidade suficiente para lidar com dinheiro, dados sensíveis e decisões que afetam clientes de verdade. Vale acompanhar se fornecedores de automação mais populares no Brasil, como Zapier e Make, vão adotar esse tipo de camada de confiabilidade como recurso nativo, ou se vão continuar deixando essa responsabilidade por conta de quem monta a automação.</p>
  `,
};
