import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "runway-praxis-1-modelo-aberto-robos",
  title: "Runway lança Praxis-1, modelo aberto que ensina robôs com vídeo",
  summary:
    "A Runway anunciou o Praxis-1, primeiro modelo de ação do mundo de peso aberto, que usa pré-treinamento em vídeo para controlar robôs de diferentes formatos sem retreinar.",
  author: "Bruno Danello",
  sourceName: "Runway Research",
  sourceUrl: "https://runway.com/research/introducing-praxis-1",
  date: "2026-09-30",
  content: `
    <p>A Runway, startup de inteligência artificial generativa para vídeo, anunciou o Praxis-1, seu primeiro modelo de ação do mundo (world-action model) de peso aberto, voltado ao controle de robôs físicos. Segundo o <a href="https://runway.com/research/introducing-praxis-1" rel="noopener noreferrer nofollow">anúncio oficial da empresa</a>, o Praxis-1 é "um modelo de política generalista para desenvolvedores e pesquisadores de robótica", capaz de funcionar em diferentes tipos de corpo de robô e ambientes sem precisar ser retreinado para cada combinação.</p>
    <p>A novidade central do Praxis-1 é a fonte dos dados de treinamento: em vez de depender apenas de demonstrações gravadas por robôs reais, que são caras e escassas, o modelo aprende a partir do mesmo pré-treinamento em vídeo de larga escala em terceira pessoa que a Runway já usa para seus modelos de geração de vídeo. A empresa afirma que, ao simular políticas de robô dentro do modelo de mundo, os resultados previstos têm correlação de 0,95 com o que de fato acontece no mundo real, um indício de que o modelo entende de forma consistente como objetos se comportam fisicamente.</p>

    <h2>Testes com braços robóticos e bases móveis</h2>
    <p>A Runway já testa o Praxis-1 com parceiros selecionados: a Noble Machines, em manipulação bimanual (dois braços trabalhando juntos); a Standard Bots, em um braço robótico de seis graus de liberdade chamado RO1; e a Ultra, em uma base móvel. Segundo a empresa, a mesma política do Praxis-1 roda nos três tipos de equipamento sem necessidade de treinar um modelo separado para cada um, o que é um dos principais obstáculos da robótica hoje: cada fabricante costuma precisar coletar seus próprios dados de demonstração para cada robô específico.</p>
    <p>Os pesos do modelo ainda não estão públicos. A Runway diz que vai liberá-los "nos próximos meses", começando pelo acesso de parceiros selecionados antes de uma disponibilização mais ampla. O lançamento acontece poucos meses depois de a empresa ter apresentado seu primeiro modelo de mundo geral, em dezembro de 2025, e mostra a aposta da Runway em sair do nicho de geração de vídeo para publicidade e cinema e entrar no mercado de <a href="/artigos/agentes-de-ia-o-futuro-do-trabalho-autonomo-explicado">automação física</a>, que hoje é dominado por empresas como a Figure AI e a Unitree, cujo avanço global em <a href="/noticias/unix-ai-expande-globalmente-prepara-ipo-robos-humanoides">robôs humanoides</a> temos acompanhado nesta coluna.</p>

    <h2>Por que isso importa para você</h2>
    <p>Robótica ainda parece distante do dia a dia de quem usa IA para trabalhar ou empreender no Brasil, mas o padrão por trás do Praxis-1 é o mesmo que já mudou texto, imagem e código: um modelo generalista, treinado numa quantidade gigantesca de dados disponíveis (no caso, vídeo da internet), que aprende a resolver um problema específico sem precisar de dados proprietários caros para cada caso de uso. Isso é relevante para quem presta consultoria em <a href="/artigos/automacao-com-ia-economize-horas-de-trabalho">automação com IA</a>, porque sinaliza que a próxima fronteira da automação não é só digital (planilhas, atendimento, geração de conteúdo), mas também física, em fábricas, armazéns e operações logísticas que ainda dependem de trabalho manual repetitivo.</p>
    <p>Para quem avalia onde investir tempo de aprendizado, vale observar que a lógica de "aprender política de robô a partir de vídeo" reduz a barreira de entrada para empresas menores entrarem em robótica, algo parecido com o que vimos quando ferramentas de IA generativa baratearam a produção de vídeo e imagem para pequenos negócios. Se os pesos do Praxis-1 forem de fato abertos como prometido, startups brasileiras de automação industrial podem adaptar o modelo para equipamentos locais sem precisar construir um laboratório de dados do zero, algo hoje restrito a poucas empresas com capital para isso.</p>

    <h2>O que observar daqui para frente</h2>
    <p>O maior teste do Praxis-1 ainda está por vir: a Runway afirma que o modelo lida melhor que abordagens anteriores com casos difíceis, como objetos transparentes, ambientes desorganizados e tecidos deformáveis, mas isso só vai ser validado de fato quando pesquisadores externos tiverem acesso aos pesos e puderem reproduzir os resultados de forma independente, algo essencial em qualquer anúncio técnico de IA. Também vale acompanhar se outros laboratórios de vídeo generativo, como a própria OpenAI com o Sora ou o Google com o Veo, seguem o mesmo caminho e lançam seus próprios modelos de ação do mundo, o que indicaria uma corrida mais ampla da indústria por transformar geração de vídeo em controle físico.</p>
    <p>Enquanto isso não acontece, o anúncio já serve como um lembrete de que a fronteira da IA segue se movendo rápido para além do texto e da imagem: assim como aconteceu com modelos de linguagem e geração de imagem, o caminho de uma pesquisa até um produto comercial tende a ser medido em meses, não em anos, e vale a pena quem trabalha com IA no Brasil acompanhar esse tipo de anúncio mesmo quando ele ainda parece distante da aplicação prática no próprio negócio.</p>

    <h2>Por que vídeo virou matéria-prima de robô</h2>
    <p>A escolha da Runway por treinar o Praxis-1 com vídeo, em vez de depender só de demonstrações feitas por robôs reais, resolve um problema antigo da robótica: coletar dados de um braço robótico executando uma tarefa específica é caro, lento e exige equipamento físico, enquanto a internet tem uma quantidade praticamente infinita de vídeos de mãos humanas manipulando objetos, pessoas cozinhando, montando móveis ou organizando uma prateleira. Ao aprender primeiro como o mundo físico se comporta a partir desses vídeos, o modelo já chega com uma base de "senso comum físico" antes mesmo de ver um robô específico, e precisa de bem menos ajuste fino para se adaptar a cada novo equipamento.</p>
    <div class="callout-box">
      <span class="callout-label">Contexto</span>
      <p>Esse tipo de modelo é chamado de "world-action model" (modelo de ação do mundo) porque combina duas capacidades: simular como o ambiente físico reage a uma ação, como um modelo de mundo tradicional, e decidir qual ação tomar para chegar a um objetivo, como um modelo de política de robótica. A Runway já vinha desenvolvendo a primeira parte, de simulação, em produtos de vídeo generativo, e o Praxis-1 é a extensão dessa tecnologia para controle físico.</p>
    </div>
    <p>Para o mercado de trabalho, essa mudança de abordagem tem um efeito indireto importante: se treinar um robô para uma nova tarefa deixar de exigir meses de coleta de dados específicos, o custo de automatizar processos físicos, como separar produtos em um centro de distribuição ou embalar pedidos em um e-commerce, tende a cair com o tempo, do mesmo jeito que o custo de automatizar tarefas digitais caiu com a popularização de ferramentas como o <a href="/artigos/agente-de-ia-chatbot-ou-automacao-qual-a-diferenca">agente de IA</a> aplicado a fluxos de atendimento e back-office. Isso não significa automação física instantânea e barata já em 2026, mas marca a direção que os grandes laboratórios de IA generativa estão tomando ao mirar além do conteúdo digital.</p>
  `,
};
