import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "tavus-griffin-video-turing-test-ia",
  title: "Tavus lança Griffin e diz ter passado o teste de Turing em vídeo",
  summary:
    "Modelo da Tavus enganou 48% dos participantes em chamadas de 1 minuto, achando que falavam com uma pessoa real, não com um avatar de IA.",
  author: "Bruno Danello",
  sourceName: "Tavus",
  sourceUrl: "https://www.tavus.io/griffin",
  date: "2026-10-01",
  content: `
    <p>A Tavus, startup americana especializada em avatares de IA em vídeo, anunciou nesta quinta-feira (1º) o Griffin, que a empresa chama de primeiro "Human Interaction Model" (modelo de interação humana) e que, segundo ela, foi o primeiro sistema a passar no teste de Turing em vídeo. Conforme a <a href="https://www.tavus.io/griffin" target="_blank" rel="noopener noreferrer nofollow">página oficial da Tavus</a>, em um estudo com pesquisadores independentes, 48% dos participantes (26 de 54 pessoas) que fizeram uma chamada de vídeo de um minuto com um avatar movido pelo Griffin acreditaram estar falando com outra pessoa real, não com uma IA.</p>

    <p>O salto é grande em relação ao histórico da própria empresa: o sistema anterior da Tavus, que combinava os modelos Phoenix-4.5, Sparrow-2 e Raven-1 (e que já tínhamos coberto <a href="/noticias/tavus-lanca-phoenix-4-5-renderizacao-humana-tempo-real">quando o Phoenix-4.5 foi lançado</a>), convenceu apenas 2,4% dos participantes (1 em 41) em teste equivalente. Griffin é descrito como um modelo "full-duplex" video-to-video: em vez de encadear etapas separadas de transcrição de voz, geração de texto e depois renderização de vídeo (o modelo chamado de "cascata", comum no setor), ele unifica percepção, decisão conversacional e geração de expressão em um único sistema que escuta, observa e responde continuamente, reavaliando a conversa em intervalos de menos de um segundo.</p>

    <h2>Como foi medido o teste e o que os números mostram</h2>
    <p>Segundo a Tavus, pesquisadores independentes recrutaram os participantes dizendo que eles fariam uma chamada de vídeo com outra pessoa (peer-to-peer), sem avisar que poderiam estar falando com uma IA. O assunto da conversa era simples e cotidiano: o que a pessoa esperava para aquele ano. Depois da chamada, os participantes responderam se suspeitavam de IA, com nível de confiança médio entre 79% e 81% entre quem respondeu corretamente que era uma IA. Mais da metade dos participantes nunca suspeitou de nada durante a ligação, e, entre os que desconfiaram, a maioria percebeu algo estranho nos primeiros 20 segundos.</p>
    <p>Em benchmarks técnicos, a empresa também afirma liderança. No VideoFDB (Video Full-Duplex Benchmark) da Nvidia, usado para avaliar como modelos interpretam e produzem comportamento audiovisual em conversa, o Griffin pontuou 3,83 de 5 na categoria de geração, superando o segundo colocado (combinação de Gemini 2.5 com Anam) por 1,03 ponto, e ficando a apenas 0,09 ponto da referência humana, de 3,92. Na categoria de percepção, marcou 3,73 de 5, também em primeiro lugar entre os 15 modelos avaliados. A latência média de resposta de áudio para vídeo foi de 0,43 segundo em GPUs H100 da Nvidia, cerca de 50% mais rápido que o concorrente mais veloz testado.</p>

    <h2>Por que isso importa para você</h2>
    <p>Avatares de IA em vídeo já são usados hoje em vendas, treinamento corporativo, atendimento ao cliente e até em <a href="/artigos/ia-para-video-criar-avatar-digital-que-fala-por-voce">vídeos pessoais de quem quer aparecer sem gravar todo dia</a>, como já exploramos aqui no Portal da AI. Um salto de 2,4% para 48% de pessoas enganadas em um teste controlado é relevante porque reduz, na prática, a distância entre "falar com um avatar que claramente parece um robô" e "falar com algo indistinguível de um ser humano real" em cenários rápidos, como uma triagem de atendimento, uma demonstração comercial inicial ou uma chamada de suporte. Para quem vende produtos ou serviços usando vídeo com apoio de IA, isso amplia a janela de uso legítimo (personalização em escala, atendimento 24 horas em vários idiomas) e, ao mesmo tempo, acende um alerta sobre uso malicioso: golpes que se aproveitam de videochamadas falsas para convencer vítimas, algo que já discutimos em reportagens anteriores sobre o <a href="/noticias/sec-golpe-ia-trading-bots-whatsapp-15-milhoes">crescimento de golpes com apoio de IA</a> no Brasil e no exterior.</p>
    <p>A própria Tavus reconhece esse risco na forma como está liberando o Griffin: o acesso, por ora, é restrito a "testadores de confiança" selecionados via formulário, em um preview de pesquisa chamado Griffin-Lite, e a empresa afirma que vai esperar a conclusão de avaliações de segurança e a implementação de recursos de divulgação (como sinalizar de forma visível que o interlocutor é uma IA) antes de abrir o acesso para o público em geral. Não há informação de preço nem previsão oficial de data de lançamento amplo.</p>

    <h2>O contexto: a corrida por vídeo conversacional em tempo real</h2>
    <p>O lançamento do Griffin acontece em um momento de disputa acelerada por quem oferece a interação em vídeo mais convincente com IA. Nas últimas semanas, o Google ampliou o avatar em vídeo do <a href="/noticias/google-gemini-3-8-live-avatar-video-tempo-real-97-idiomas">Gemini 3.8 Live para 97 idiomas</a> e depois levou o mesmo recurso para empresas com o <a href="/noticias/google-gemini-3-8-live-avatar-empresas">Gemini 3.8 Live Avatar corporativo</a>, enquanto startups de vídeo gerado por IA como a Higgsfield já relataram <a href="/noticias/higgsfield-video-ia-1-bilhao-receita-anualizada">receita anualizada de US$ 1 bilhão</a>. A diferença central do Griffin em relação a esses concorrentes é o foco específico em conversa bidirecional em tempo real, cara a cara, em vez de geração de vídeo a partir de roteiro ou texto, o que é uma categoria de produto distinta e tecnicamente mais difícil de acertar, já que exige reagir à fala e às expressões do interlocutor humano no mesmo instante em que ele fala, sem os cortes e pausas perceptíveis que ainda denunciam a maioria dos assistentes de vídeo atuais.</p>
    <p>Vale lembrar que o resultado do teste de Turing em vídeo da Tavus, por ora, não passou por auditoria de terceiros independente da própria empresa (os pesquisadores foram contratados pela Tavus, mesmo que operando de forma isolada do time de produto) e a plataforma de recrutamento dos participantes não foi divulgada publicamente. Isso não invalida os números, mas é um bom motivo para tratar o resultado como um indicador forte de progresso técnico, e não como prova definitiva e isenta de qualquer interesse comercial, até que o Griffin esteja disponível para testes mais amplos e replicação por terceiros.</p>
  `,
};
