import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "tse-restricao-ia-reta-final-eleicoes-2026",
  title: "TSE proíbe novo conteúdo com IA sobre candidatos a partir desta quinta",
  summary:
    "A partir de 1º de outubro vale o silêncio eleitoral para IA: nenhum conteúdo sintético novo sobre candidatos pode ser publicado até 24h após a votação.",
  author: "Bruno Danello",
  sourceName: "Jamildo",
  sourceUrl: "https://jamildo.com/politica/eleicoes-2026-tse-restringe-uso-de-inteligencia-artificial-na-reta-final-da-votacao.html",
  date: "2026-10-01",
  content: `
    <p>A partir desta quinta-feira (1º), entrou em vigor o período de restrição máxima ao uso de inteligência artificial nas Eleições 2026. Pela regra do Tribunal Superior Eleitoral (TSE), fica proibido publicar, republicar ou impulsionar qualquer conteúdo sintético novo (produzido ou alterado por IA) que envolva imagem, voz ou manifestação de candidato ou pessoa pública, mesmo que o material esteja devidamente identificado como feito por IA. Segundo reportagem do <a href="https://jamildo.com/politica/eleicoes-2026-tse-restringe-uso-de-inteligencia-artificial-na-reta-final-da-votacao.html" target="_blank" rel="noopener noreferrer nofollow">Jamildo</a>, a janela de silêncio vale até o primeiro turno, marcado para 4 de outubro, e se estende por 24 horas após o fim da votação.</p>

    <p>A base legal é a Resolução TSE nº 23.755/2026, que alterou o artigo 9º-B, § 3º-A, da Resolução TSE nº 23.610/2019. A regra não proíbe qualquer uso de IA na campanha, mas fecha a torneira justamente no momento em que não há mais tempo hábil para desmentir um conteúdo manipulado antes de o eleitor votar. Ajustes técnicos simples, como melhoria de qualidade de imagem ou áudio, vinhetas e elementos gráficos padrão, continuam liberados; o que fica vedado é criar ou alterar de forma sintética a imagem, a voz ou a fala de uma pessoa real.</p>

    <h2>Por que o TSE chegou a esse recorte específico</h2>
    <p>A preocupação central do tribunal são os deepfakes eleitorais: vídeos e áudios gerados por IA que simulam um candidato dizendo algo que ele nunca disse. Em sessão anterior, por 5 votos a 2, o TSE já havia fixado a tese de que deepfake é o conteúdo sintético que apresenta grau de realismo suficiente para criar, reproduzir ou alterar a imagem, a voz ou a manifestação de uma pessoa viva, falecida ou fictícia. Fora da janela de silêncio, a regra geral das Eleições 2026 já exige que qualquer propaganda com conteúdo sintético multimídia traga identificação clara, destacada e acessível de que foi criada ou alterada por IA, informando inclusive qual ferramenta foi usada.</p>
    <p>O caso não é isolado. Candidatos indicados por Jair Bolsonaro já alegaram ter tido a própria voz clonada por IA para disseminar desinformação na reta final da campanha, e a Polícia Federal já havia aberto mais de 1.200 inquéritos sobre crimes eleitorais só em 2026. O Portal da AI também mostrou como a <a href="/noticias/its-rio-boca-de-ia-perplexity-recomenda-candidatos-tse">Perplexity chegou a recomendar candidatos de forma indevida</a> em testes conduzidos pelo ITS-Rio, episódio que reforçou a preocupação do TSE com IA influenciando o voto de forma não transparente, assim como o lançamento do <a href="/noticias/tse-lanca-chatvote-assistente-ia-eleicoes-2026">ChatVote, assistente oficial do próprio tribunal</a>, mostra que a Justiça Eleitoral tenta usar IA de forma controlada enquanto restringe o uso por terceiros.</p>

    <h2>Por que isso importa para você</h2>
    <p>Se você trabalha com marketing político, assessoria de comunicação ou gestão de redes sociais de candidatos, a regra tem efeito prático imediato: qualquer peça nova com voz sintetizada, vídeo gerado por IA ou imagem manipulada de um candidato precisa ficar parada entre agora e o fim da janela de silêncio, independentemente de estar identificada. Postar mesmo um conteúdo rotulado como "gerado por IA" nesse intervalo já configura infração, o que muda o fluxo de aprovação de qualquer equipe que ainda tinha peças programadas para os últimos dias de campanha.</p>
    <p>Para quem usa IA no dia a dia fora da política, o episódio é um bom alerta sobre como identificar conteúdo sintético antes de compartilhar algo que pode ser falso, especialmente em grupos de WhatsApp e redes sociais durante a semana de votação. Nosso guia sobre <a href="/artigos/deepfakes-ia-identificar-conteudo-falso-proteger-reputacao">como identificar deepfakes e proteger sua reputação online</a> explica os sinais mais comuns de manipulação por IA em vídeo e áudio, e vale compartilhar justamente agora, quando a desinformação eleitoral tende a circular mais.</p>

    <h2>O que observar até o fim da votação</h2>
    <p>Quem administra páginas e perfis de campanhas deve revisar agendamentos de posts para os próximos dias e remover qualquer peça com conteúdo sintético novo que ainda não tenha sido publicada, já que republicar material antigo também está vedado dentro da janela. Fica permitido, por outro lado, continuar impulsionando conteúdo humano tradicional (sem IA) e materiais já identificados que não envolvam deepfake, segundo as regras gerais fixadas desde março pelo TSE. Vale lembrar também que a vedação recai sobre conteúdo sintético envolvendo pessoas reais (candidatos, autoridades, apresentadores), e não sobre toda e qualquer peça de campanha: uma arte estática com foto real do candidato, por exemplo, não entra na mesma categoria de risco que um vídeo ou áudio gerado por IA simulando a fala dele.</p>
    <p>Episódios de golpes com voz clonada por IA, como o caso de um banco italiano que levou a um prejuízo de <a href="/noticias/golpe-voz-ia-banco-italiano-fideuram-95-milhoes">95 milhões de euros</a> e o esquema de bots de negociação denunciado pela <a href="/noticias/sec-golpe-ia-trading-bots-whatsapp-15-milhoes">SEC nos Estados Unidos</a>, mostram que a mesma tecnologia usada para enganar eleitores também é usada para aplicar golpes financeiros. Vale manter a atenção redobrada a mensagens, áudios e vídeos recebidos por WhatsApp nos próximos dias, tanto no contexto eleitoral quanto fora dele, e desconfiar de qualquer conteúdo urgente demais para ser verificado antes de agir.</p>

    <h2>Como fica a fiscalização na prática</h2>
    <p>A fiscalização do cumprimento da janela de silêncio cabe à Justiça Eleitoral, que pode determinar a retirada imediata de conteúdo irregular das plataformas e abrir representação contra quem publicou o material, com possibilidade de multa e, em casos mais graves, impacto sobre a própria candidatura envolvida. As plataformas de redes sociais e mensageria também têm obrigação de colaborar na remoção de conteúdo quando notificadas, o que inclui WhatsApp, Instagram, TikTok, YouTube e X, principais canais de disseminação de propaganda eleitoral digital no país. Denúncias podem ser feitas diretamente pelo aplicativo Pardal, usado pela Justiça Eleitoral para recolher evidências de propaganda irregular, ou pelos canais oficiais do TSE e dos tribunais regionais eleitorais em cada estado.</p>
    <blockquote>
      <span class="callout-label">Resumo da regra</span>
      Entre 1º e 5 de outubro (72h antes do fim da votação do primeiro turno até 24h depois), nenhum conteúdo sintético novo envolvendo imagem, voz ou fala de candidato ou pessoa pública pode ser publicado, republicado ou impulsionado, mesmo identificado como feito por IA.
    </blockquote>
    <p>Para quem acompanha o noticiário sobre IA e eleições fora do Brasil, o movimento do TSE segue uma tendência já vista em outros países, que têm testado janelas de restrição semelhantes diante do avanço de ferramentas de geração de voz e vídeo cada vez mais convincentes e baratas de usar. A diferença é que o Brasil optou por uma regra objetiva de prazo fixo, em vez de depender apenas de uma avaliação caso a caso sobre se um conteúdo é ou não enganoso, o que facilita tanto a fiscalização pela Justiça Eleitoral quanto o entendimento de quem produz propaganda política sobre o que pode e o que não pode fazer nos últimos dias antes da votação.</p>
  `,
};
