import type { NewsItem } from "@/lib/types";

export const item: NewsItem = {
  slug: "warren-investiga-isencao-fiscal-ia-big-tech",
  title: "Warren investiga isenção fiscal bilionária de big techs em data centers de IA",
  summary:
    "Warren lidera pedido a Meta, Amazon, Google e Microsoft para detalhar deduções fiscais usadas em data centers de IA, com prazo até 12 de outubro.",
  author: "Bruno Danello",
  sourceName: "Gabinete da senadora Elizabeth Warren",
  sourceUrl:
    "https://www.warren.senate.gov/newsroom/press-releases/warren-lawmakers-open-investigation-into-republicans-massive-trump-tax-subsidies-for-big-techs-ai-spending/",
  date: "2026-09-28",
  content: `
    <p>A senadora Elizabeth Warren (Democrata-Massachusetts) enviou, em 28 de setembro, cartas a Amazon, Meta, Alphabet (dona do Google) e Microsoft exigindo que as empresas detalhem as deduções fiscais bilionárias que vêm usando para financiar a expansão de data centers de inteligência artificial. Segundo o <a href="https://www.warren.senate.gov/newsroom/press-releases/warren-lawmakers-open-investigation-into-republicans-massive-trump-tax-subsidies-for-big-techs-ai-spending/" target="_blank" rel="noopener noreferrer nofollow">comunicado oficial do gabinete da senadora</a>, a iniciativa também foi assinada pelos senadores Elissa Slotkin, Jeff Merkley, Bernie Sanders, Richard Blumenthal e Tina Smith, e pede que as quatro companhias respondam até 12 de outubro.</p>

    <p>O pedido tem dois eixos: primeiro, que cada empresa divulgue exatamente quanto já deduziu do imposto de renda federal usando os benefícios criados pela "One, Big, Beautiful Bill Act" (OBBBA), a lei tributária sancionada em 2025 que tornou permanente a depreciação acelerada de 100% para investimentos em equipamentos, incluindo servidores e infraestrutura de data center. Segundo, que revelem quais atividades de lobby fizeram para garantir a aprovação desses benefícios antes da lei ser votada no Congresso.</p>

    <h2>Os números por trás da investigação</h2>
    <p>O comunicado dos senadores cita cálculos que ajudam a entender por que o tema virou prioridade política. A arrecadação de imposto de renda corporativo federal nos Estados Unidos caiu 25% em 2026 na comparação anual, mesmo com os lucros das grandes empresas de tecnologia em alta. No caso específico da Microsoft, a carga tributária federal caiu mais de US$ 11 bilhões entre os anos fiscais de 2025 e 2026, período em que a receita antes de impostos da empresa cresceu US$ 42,3 bilhões. Já a Meta reduziu sua conta de impostos federais em cerca de US$ 7 bilhões entre 2024 e 2025, com aumento de mais de US$ 15 bilhões na receita antes de impostos no mesmo intervalo.</p>
    <p>Os senadores também destacam que cada uma das quatro empresas doou US$ 1 milhão para o comitê de posse do presidente Donald Trump, e que a extensão permanente da depreciação acelerada, aprovada na OBBBA, deve custar aos cofres públicos americanos US$ 362,7 bilhões ao longo de dez anos, segundo estimativas citadas no documento. Para os parlamentares democratas, o pacote de benefícios fiscais aprovado sob a liderança republicana no Congresso funcionou como um subsídio direto à corrida bilionária das big techs por capacidade computacional, num momento em que o mesmo grupo de empresas vem investindo centenas de bilhões de dólares na construção de data centers como os do projeto Stargate, que já enfrentou soluços como a <a href="/noticias/oracle-force-majeure-data-center-stargate-novo-mexico">cláusula de força maior acionada pela Oracle em um dos empreendimentos no Novo México</a>.</p>

    <h2>Por que isso importa para você</h2>
    <p>Para quem acompanha o mercado de IA no Brasil, com olhos em investir, empreender ou simplesmente entender para onde vai o dinheiro que sustenta os modelos que usamos no dia a dia, essa investigação escancara um ponto pouco discutido: parte relevante da corrida bilionária por infraestrutura de IA nos Estados Unidos é viabilizada por renúncia fiscal, não só por caixa das próprias empresas. Isso ajuda a explicar como companhias como a Oracle conseguem anunciar <a href="/noticias/oracle-backlog-664-bilhoes-nuvem-ia">um backlog recorde de US$ 664 bilhões em contratos de nuvem de IA</a> e como a Microsoft consegue <a href="/noticias/microsoft-triplica-capacidade-data-centers-ia">triplicar sua capacidade de data centers</a> num ritmo que seria mais difícil de sustentar sem esse tipo de benefício.</p>
    <p>Na prática, quem monta negócio em cima de API de IA, revende créditos de nuvem ou depende do preço competitivo dos grandes modelos se beneficia indiretamente desse subsídio, porque parte do custo de treinar e rodar modelos gigantes é hoje socializado via renúncia de arrecadação nos Estados Unidos. Ao mesmo tempo, é um lembrete de que esse tipo de vantagem depende de decisão política e pode mudar: se o Congresso americano decidir rever os termos da OBBBA em resposta à pressão dessa investigação, o custo de operar infraestrutura de IA em larga escala pode subir, o que tende a se refletir, com o tempo, em preços de API e assinaturas em qualquer lugar do mundo, inclusive no Brasil.</p>

    <h2>Um capítulo a mais na tensão entre Big Tech e Congresso</h2>
    <p>A investigação de Warren não nasce isolada. Ela chega poucos dias depois de o <a href="/noticias/trump-ceos-ia-assinam-acordo-autorregulacao-casa-branca">Trump reunir os principais CEOs de IA na Casa Branca para assinar um acordo voluntário de autorregulação</a>, sem força de lei, e no mesmo mês em que um grupo bipartidário de senadores já havia apresentado <a href="/noticias/senadores-eua-projeto-lei-transparencia-ia-systems-transparency-act">um projeto de lei para forçar empresas de IA a divulgar mais informações sobre seus sistemas</a>. O padrão que emerge é o de um Congresso dividido entre parlamentares que aceitam a autorregulação promovida pela Casa Branca e um grupo que tenta usar as ferramentas que tem, como pedidos formais de transparência fiscal, para forçar mais accountability das mesmas empresas.</p>
    <p>Vale notar que pedir informações não é o mesmo que obrigar a mudança de política: as quatro empresas notificadas podem simplesmente ignorar o prazo de 12 de outubro ou responder de forma parcial, já que a carta não tem poder de intimação judicial. Ainda assim, esse tipo de pressão pública já se mostrou capaz de gerar desdobramentos em outros momentos da relação entre Congresso e big techs, seja com audiências públicas, seja com projetos de lei subsequentes tentando fechar as brechas identificadas.</p>

    <h2>O que observar daqui para frente</h2>
    <p>Vale acompanhar se Amazon, Meta, Alphabet e Microsoft vão de fato responder até o prazo estipulado, e com que nível de detalhe. Historicamente, esse tipo de pedido costuma render respostas genéricas que reafirmam o cumprimento da legislação vigente sem abrir números específicos por linha de investimento. Também merece atenção se outros parlamentares, republicanos ou democratas de estados diferentes, vão se somar à cobrança, e se o tema da renúncia fiscal em IA vai entrar na pauta das eleições de meio de mandato nos Estados Unidos em 2026, dado o desgaste político de associar benefícios bilionários a empresas de tecnologia com a queda simultânea na arrecadação federal.</p>
    <p>Para quem constrói negócio em cima de infraestrutura de nuvem e IA, o recado é acompanhar de perto esse tipo de movimento regulatório nos Estados Unidos com a mesma atenção dada a lançamentos de novos modelos: mudanças na política tributária americana tendem a levar meses ou anos para se refletir em preço, mas quando acontecem, afetam toda a cadeia, do provedor de nuvem até quem paga a assinatura de uma ferramenta de IA aqui no Brasil.</p>
  `,
};
